/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queryExportEventsQueryResults } from "../../funcs/queryExportEventsQueryResults.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.QueryEventsRequestBody$inboundSchema,
};

export const tool$queryExportEventsQueryResults: ToolDefinition<typeof args> = {
  name: "query-export-events-query-results",
  description: `Export Events Query Results`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await queryExportEventsQueryResults(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
