/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { InkeepAnalyticsCore } from "../core.js";
import { conversationsGet } from "../funcs/conversationsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ConversationsGetQueryData = components.Conversation;

export function prefetchConversationsGet(
  queryClient: QueryClient,
  client$: InkeepAnalyticsCore,
  security: operations.GetConversationSecurity,
  request: operations.GetConversationRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildConversationsGetQuery(
      client$,
      security,
      request,
      options,
    ),
  });
}

export function buildConversationsGetQuery(
  client$: InkeepAnalyticsCore,
  security: operations.GetConversationSecurity,
  request: operations.GetConversationRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ConversationsGetQueryData>;
} {
  return {
    queryKey: queryKeyConversationsGet(request.id),
    queryFn: async function conversationsGetQueryFn(
      ctx,
    ): Promise<ConversationsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(conversationsGet(
        client$,
        security,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyConversationsGet(id: string): QueryKey {
  return ["@inkeep/inkeep-analytics", "conversations", "get", id];
}
