/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { InkeepAnalyticsError } from "../models/errors/inkeepanalyticserror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useInkeepAnalyticsContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildConversationGetConversationByExternalIdQuery,
  ConversationGetConversationByExternalIdQueryData,
  prefetchConversationGetConversationByExternalId,
  queryKeyConversationGetConversationByExternalId,
} from "./conversationGetConversationByExternalId.core.js";
export {
  buildConversationGetConversationByExternalIdQuery,
  type ConversationGetConversationByExternalIdQueryData,
  prefetchConversationGetConversationByExternalId,
  queryKeyConversationGetConversationByExternalId,
};

export type ConversationGetConversationByExternalIdQueryError =
  | errors.BadRequest
  | errors.Unauthorized
  | errors.Forbidden
  | errors.NotFound
  | errors.UnprocessableEntity
  | errors.InternalServerError
  | InkeepAnalyticsError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get Conversation by External ID
 */
export function useConversationGetConversationByExternalId(
  request: operations.GetConversationByExternalIdRequest,
  options?: QueryHookOptions<
    ConversationGetConversationByExternalIdQueryData,
    ConversationGetConversationByExternalIdQueryError
  >,
): UseQueryResult<
  ConversationGetConversationByExternalIdQueryData,
  ConversationGetConversationByExternalIdQueryError
> {
  const client = useInkeepAnalyticsContext();
  return useQuery({
    ...buildConversationGetConversationByExternalIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get Conversation by External ID
 */
export function useConversationGetConversationByExternalIdSuspense(
  request: operations.GetConversationByExternalIdRequest,
  options?: SuspenseQueryHookOptions<
    ConversationGetConversationByExternalIdQueryData,
    ConversationGetConversationByExternalIdQueryError
  >,
): UseSuspenseQueryResult<
  ConversationGetConversationByExternalIdQueryData,
  ConversationGetConversationByExternalIdQueryError
> {
  const client = useInkeepAnalyticsContext();
  return useSuspenseQuery({
    ...buildConversationGetConversationByExternalIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setConversationGetConversationByExternalIdData(
  client: QueryClient,
  queryKeyBase: [externalId: string],
  data: ConversationGetConversationByExternalIdQueryData,
): ConversationGetConversationByExternalIdQueryData | undefined {
  const key = queryKeyConversationGetConversationByExternalId(...queryKeyBase);

  return client.setQueryData<ConversationGetConversationByExternalIdQueryData>(
    key,
    data,
  );
}

export function invalidateConversationGetConversationByExternalId(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[externalId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@inkeep/inkeep-analytics",
      "conversation",
      "getConversationByExternalId",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllConversationGetConversationByExternalId(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@inkeep/inkeep-analytics",
      "conversation",
      "getConversationByExternalId",
    ],
  });
}
