/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { InkeepAnalyticsCore } from "../core.js";
import { postQueryPropertyKeys } from "../funcs/postQueryPropertyKeys.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useInkeepAnalyticsContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type PostQueryPropertyKeysMutationVariables = {
  security: operations.PostQueryPropertyKeysSecurity;
  request?: components.PropertyKeysRequestBody | undefined;
  options?: RequestOptions;
};

export type PostQueryPropertyKeysMutationData =
  components.PropertyKeysResponseBody;

export function usePostQueryPropertyKeysMutation(
  options?: MutationHookOptions<
    PostQueryPropertyKeysMutationData,
    Error,
    PostQueryPropertyKeysMutationVariables
  >,
): UseMutationResult<
  PostQueryPropertyKeysMutationData,
  Error,
  PostQueryPropertyKeysMutationVariables
> {
  const client = useInkeepAnalyticsContext();
  return useMutation({
    ...buildPostQueryPropertyKeysMutation(client, options),
    ...options,
  });
}

export function mutationKeyPostQueryPropertyKeys(): MutationKey {
  return ["@inkeep/inkeep-analytics", "postQueryPropertyKeys"];
}

export function buildPostQueryPropertyKeysMutation(
  client$: InkeepAnalyticsCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: PostQueryPropertyKeysMutationVariables,
  ) => Promise<PostQueryPropertyKeysMutationData>;
} {
  return {
    mutationKey: mutationKeyPostQueryPropertyKeys(),
    mutationFn: function postQueryPropertyKeysMutationFn({
      security,
      request,
      options,
    }): Promise<PostQueryPropertyKeysMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(postQueryPropertyKeys(
        client$,
        security,
        request,
        mergedOptions,
      ));
    },
  };
}
