/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { InkeepAnalyticsCore } from "../core.js";
import { queryExportConversationsQueryResults } from "../funcs/queryExportConversationsQueryResults.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { InkeepAnalyticsError } from "../models/errors/inkeepanalyticserror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useInkeepAnalyticsContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type QueryExportConversationsQueryResultsMutationVariables = {
  request: components.QueryConversationsRequestBody;
  options?: RequestOptions;
};

export type QueryExportConversationsQueryResultsMutationData = ReadableStream<
  Uint8Array
>;

export type QueryExportConversationsQueryResultsMutationError =
  | errors.BadRequest
  | errors.Unauthorized
  | errors.Forbidden
  | errors.UnprocessableEntity
  | errors.InternalServerError
  | InkeepAnalyticsError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Export Conversations Query Results
 */
export function useQueryExportConversationsQueryResultsMutation(
  options?: MutationHookOptions<
    QueryExportConversationsQueryResultsMutationData,
    QueryExportConversationsQueryResultsMutationError,
    QueryExportConversationsQueryResultsMutationVariables
  >,
): UseMutationResult<
  QueryExportConversationsQueryResultsMutationData,
  QueryExportConversationsQueryResultsMutationError,
  QueryExportConversationsQueryResultsMutationVariables
> {
  const client = useInkeepAnalyticsContext();
  return useMutation({
    ...buildQueryExportConversationsQueryResultsMutation(client, options),
    ...options,
  });
}

export function mutationKeyQueryExportConversationsQueryResults(): MutationKey {
  return [
    "@inkeep/inkeep-analytics",
    "Query",
    "exportConversationsQueryResults",
  ];
}

export function buildQueryExportConversationsQueryResultsMutation(
  client$: InkeepAnalyticsCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: QueryExportConversationsQueryResultsMutationVariables,
  ) => Promise<QueryExportConversationsQueryResultsMutationData>;
} {
  return {
    mutationKey: mutationKeyQueryExportConversationsQueryResults(),
    mutationFn: function queryExportConversationsQueryResultsMutationFn({
      request,
      options,
    }): Promise<QueryExportConversationsQueryResultsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(queryExportConversationsQueryResults(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
