/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { InkeepAnalyticsCore } from "../core.js";
import { queryExportFeedbackQueryResults } from "../funcs/queryExportFeedbackQueryResults.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useInkeepAnalyticsContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type QueryExportFeedbackQueryResultsMutationVariables = {
  request: components.QueryFeedbackRequestBody;
  options?: RequestOptions;
};

export type QueryExportFeedbackQueryResultsMutationData = ReadableStream<
  Uint8Array
>;

/**
 * Export Feedback Query Results
 */
export function useQueryExportFeedbackQueryResultsMutation(
  options?: MutationHookOptions<
    QueryExportFeedbackQueryResultsMutationData,
    Error,
    QueryExportFeedbackQueryResultsMutationVariables
  >,
): UseMutationResult<
  QueryExportFeedbackQueryResultsMutationData,
  Error,
  QueryExportFeedbackQueryResultsMutationVariables
> {
  const client = useInkeepAnalyticsContext();
  return useMutation({
    ...buildQueryExportFeedbackQueryResultsMutation(client, options),
    ...options,
  });
}

export function mutationKeyQueryExportFeedbackQueryResults(): MutationKey {
  return ["@inkeep/inkeep-analytics", "Query", "exportFeedbackQueryResults"];
}

export function buildQueryExportFeedbackQueryResultsMutation(
  client$: InkeepAnalyticsCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: QueryExportFeedbackQueryResultsMutationVariables,
  ) => Promise<QueryExportFeedbackQueryResultsMutationData>;
} {
  return {
    mutationKey: mutationKeyQueryExportFeedbackQueryResults(),
    mutationFn: function queryExportFeedbackQueryResultsMutationFn({
      request,
      options,
    }): Promise<QueryExportFeedbackQueryResultsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(queryExportFeedbackQueryResults(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
