/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exportExport } from "../funcs/exportExport.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Export extends ClientSDK {
  /**
   * Query Export
   */
  async export(
    request: operations.ExportQueryRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(exportExport(
      this,
      request,
      options,
    ));
  }
}
