/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetConversationByExternalIdRequest = {
  externalId: string;
};

/** @internal */
export const GetConversationByExternalIdRequest$inboundSchema: z.ZodType<
  GetConversationByExternalIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  externalId: z.string(),
});
/** @internal */
export type GetConversationByExternalIdRequest$Outbound = {
  externalId: string;
};

/** @internal */
export const GetConversationByExternalIdRequest$outboundSchema: z.ZodType<
  GetConversationByExternalIdRequest$Outbound,
  z.ZodTypeDef,
  GetConversationByExternalIdRequest
> = z.object({
  externalId: z.string(),
});

export function getConversationByExternalIdRequestToJSON(
  getConversationByExternalIdRequest: GetConversationByExternalIdRequest,
): string {
  return JSON.stringify(
    GetConversationByExternalIdRequest$outboundSchema.parse(
      getConversationByExternalIdRequest,
    ),
  );
}
export function getConversationByExternalIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetConversationByExternalIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetConversationByExternalIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConversationByExternalIdRequest' from JSON`,
  );
}
