/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OpenAIConversation,
  OpenAIConversation$inboundSchema,
  OpenAIConversation$Outbound,
  OpenAIConversation$outboundSchema,
} from "./openaiconversation.js";
import {
  SupportCopilotConversation,
  SupportCopilotConversation$inboundSchema,
  SupportCopilotConversation$Outbound,
  SupportCopilotConversation$outboundSchema,
} from "./supportcopilotconversation.js";
import {
  SupportTicketConversation,
  SupportTicketConversation$inboundSchema,
  SupportTicketConversation$Outbound,
  SupportTicketConversation$outboundSchema,
} from "./supportticketconversation.js";

export type Conversation =
  | OpenAIConversation
  | SupportTicketConversation
  | SupportCopilotConversation;

/** @internal */
export const Conversation$inboundSchema: z.ZodType<
  Conversation,
  z.ZodTypeDef,
  unknown
> = z.union([
  OpenAIConversation$inboundSchema,
  SupportTicketConversation$inboundSchema,
  SupportCopilotConversation$inboundSchema,
]);
/** @internal */
export type Conversation$Outbound =
  | OpenAIConversation$Outbound
  | SupportTicketConversation$Outbound
  | SupportCopilotConversation$Outbound;

/** @internal */
export const Conversation$outboundSchema: z.ZodType<
  Conversation$Outbound,
  z.ZodTypeDef,
  Conversation
> = z.union([
  OpenAIConversation$outboundSchema,
  SupportTicketConversation$outboundSchema,
  SupportCopilotConversation$outboundSchema,
]);

export function conversationToJSON(conversation: Conversation): string {
  return JSON.stringify(Conversation$outboundSchema.parse(conversation));
}
export function conversationFromJSON(
  jsonString: string,
): SafeParseResult<Conversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Conversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Conversation' from JSON`,
  );
}
