/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CreateOpenAIConversation,
  CreateOpenAIConversation$inboundSchema,
  CreateOpenAIConversation$Outbound,
  CreateOpenAIConversation$outboundSchema,
} from "./createopenaiconversation.js";
import {
  CreateSupportCopilotConversation,
  CreateSupportCopilotConversation$inboundSchema,
  CreateSupportCopilotConversation$Outbound,
  CreateSupportCopilotConversation$outboundSchema,
} from "./createsupportcopilotconversation.js";
import {
  CreateSupportTicketConversation,
  CreateSupportTicketConversation$inboundSchema,
  CreateSupportTicketConversation$Outbound,
  CreateSupportTicketConversation$outboundSchema,
} from "./createsupportticketconversation.js";

export type CreateConversation =
  | CreateOpenAIConversation
  | CreateSupportTicketConversation
  | CreateSupportCopilotConversation;

/** @internal */
export const CreateConversation$inboundSchema: z.ZodType<
  CreateConversation,
  z.ZodTypeDef,
  unknown
> = z.union([
  CreateOpenAIConversation$inboundSchema,
  CreateSupportTicketConversation$inboundSchema,
  CreateSupportCopilotConversation$inboundSchema,
]);
/** @internal */
export type CreateConversation$Outbound =
  | CreateOpenAIConversation$Outbound
  | CreateSupportTicketConversation$Outbound
  | CreateSupportCopilotConversation$Outbound;

/** @internal */
export const CreateConversation$outboundSchema: z.ZodType<
  CreateConversation$Outbound,
  z.ZodTypeDef,
  CreateConversation
> = z.union([
  CreateOpenAIConversation$outboundSchema,
  CreateSupportTicketConversation$outboundSchema,
  CreateSupportCopilotConversation$outboundSchema,
]);

export function createConversationToJSON(
  createConversation: CreateConversation,
): string {
  return JSON.stringify(
    CreateConversation$outboundSchema.parse(createConversation),
  );
}
export function createConversationFromJSON(
  jsonString: string,
): SafeParseResult<CreateConversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateConversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateConversation' from JSON`,
  );
}
