/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EventsAggregationSelection,
  EventsAggregationSelection$inboundSchema,
  EventsAggregationSelection$Outbound,
  EventsAggregationSelection$outboundSchema,
} from "./eventsaggregationselection.js";
import {
  EventsSimpleFieldSelection,
  EventsSimpleFieldSelection$inboundSchema,
  EventsSimpleFieldSelection$Outbound,
  EventsSimpleFieldSelection$outboundSchema,
} from "./eventssimplefieldselection.js";
import {
  EventsTimeBasedGroupBySelection,
  EventsTimeBasedGroupBySelection$inboundSchema,
  EventsTimeBasedGroupBySelection$Outbound,
  EventsTimeBasedGroupBySelection$outboundSchema,
} from "./eventstimebasedgroupbyselection.js";

/**
 * Fields to select from events
 */
export type EventsSelection =
  | EventsAggregationSelection
  | EventsTimeBasedGroupBySelection
  | EventsSimpleFieldSelection;

/** @internal */
export const EventsSelection$inboundSchema: z.ZodType<
  EventsSelection,
  z.ZodTypeDef,
  unknown
> = z.union([
  EventsAggregationSelection$inboundSchema,
  EventsTimeBasedGroupBySelection$inboundSchema,
  EventsSimpleFieldSelection$inboundSchema,
]);
/** @internal */
export type EventsSelection$Outbound =
  | EventsAggregationSelection$Outbound
  | EventsTimeBasedGroupBySelection$Outbound
  | EventsSimpleFieldSelection$Outbound;

/** @internal */
export const EventsSelection$outboundSchema: z.ZodType<
  EventsSelection$Outbound,
  z.ZodTypeDef,
  EventsSelection
> = z.union([
  EventsAggregationSelection$outboundSchema,
  EventsTimeBasedGroupBySelection$outboundSchema,
  EventsSimpleFieldSelection$outboundSchema,
]);

export function eventsSelectionToJSON(
  eventsSelection: EventsSelection,
): string {
  return JSON.stringify(EventsSelection$outboundSchema.parse(eventsSelection));
}
export function eventsSelectionFromJSON(
  jsonString: string,
): SafeParseResult<EventsSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsSelection' from JSON`,
  );
}
