/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TimeUnit,
  TimeUnit$inboundSchema,
  TimeUnit$outboundSchema,
} from "./timeunit.js";

export const EventsTimeBasedGroupBySelectionField = {
  Id: "id",
  OrganizationId: "organizationId",
  MessageId: "messageId",
  ConversationId: "conversationId",
  CreatedAt: "createdAt",
  ProjectId: "projectId",
  IntegrationId: "integrationId",
  EventType: "eventType",
  Type: "type",
  SearchQuery: "searchQuery",
  Properties: "properties",
  UserProperties: "userProperties",
} as const;
export type EventsTimeBasedGroupBySelectionField = ClosedEnum<
  typeof EventsTimeBasedGroupBySelectionField
>;

export type EventsTimeBasedGroupBySelection = {
  type: "time";
  /**
   * Valid time units for time-based operations
   */
  timeUnit: TimeUnit;
  field?: EventsTimeBasedGroupBySelectionField | undefined;
};

/** @internal */
export const EventsTimeBasedGroupBySelectionField$inboundSchema:
  z.ZodNativeEnum<typeof EventsTimeBasedGroupBySelectionField> = z.nativeEnum(
    EventsTimeBasedGroupBySelectionField,
  );
/** @internal */
export const EventsTimeBasedGroupBySelectionField$outboundSchema:
  z.ZodNativeEnum<typeof EventsTimeBasedGroupBySelectionField> =
    EventsTimeBasedGroupBySelectionField$inboundSchema;

/** @internal */
export const EventsTimeBasedGroupBySelection$inboundSchema: z.ZodType<
  EventsTimeBasedGroupBySelection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("time"),
  timeUnit: TimeUnit$inboundSchema,
  field: EventsTimeBasedGroupBySelectionField$inboundSchema.optional(),
});
/** @internal */
export type EventsTimeBasedGroupBySelection$Outbound = {
  type: "time";
  timeUnit: string;
  field?: string | undefined;
};

/** @internal */
export const EventsTimeBasedGroupBySelection$outboundSchema: z.ZodType<
  EventsTimeBasedGroupBySelection$Outbound,
  z.ZodTypeDef,
  EventsTimeBasedGroupBySelection
> = z.object({
  type: z.literal("time"),
  timeUnit: TimeUnit$outboundSchema,
  field: EventsTimeBasedGroupBySelectionField$outboundSchema.optional(),
});

export function eventsTimeBasedGroupBySelectionToJSON(
  eventsTimeBasedGroupBySelection: EventsTimeBasedGroupBySelection,
): string {
  return JSON.stringify(
    EventsTimeBasedGroupBySelection$outboundSchema.parse(
      eventsTimeBasedGroupBySelection,
    ),
  );
}
export function eventsTimeBasedGroupBySelectionFromJSON(
  jsonString: string,
): SafeParseResult<EventsTimeBasedGroupBySelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsTimeBasedGroupBySelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsTimeBasedGroupBySelection' from JSON`,
  );
}
