/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EventsFilterAND,
  EventsFilterAND$inboundSchema,
  EventsFilterAND$Outbound,
  EventsFilterAND$outboundSchema,
} from "./eventsfilterand.js";
import {
  EventsFilterCondition,
  EventsFilterCondition$inboundSchema,
  EventsFilterCondition$Outbound,
  EventsFilterCondition$outboundSchema,
} from "./eventsfiltercondition.js";
import {
  EventsFilterOR,
  EventsFilterOR$inboundSchema,
  EventsFilterOR$Outbound,
  EventsFilterOR$outboundSchema,
} from "./eventsfilteror.js";

export type EventsFilter =
  | EventsFilterCondition
  | EventsFilterAND
  | EventsFilterOR;

/** @internal */
export const EventsFilter$inboundSchema: z.ZodType<
  EventsFilter,
  z.ZodTypeDef,
  unknown
> = z.union([
  EventsFilterCondition$inboundSchema,
  z.lazy(() => EventsFilterAND$inboundSchema),
  z.lazy(() => EventsFilterOR$inboundSchema),
]);
/** @internal */
export type EventsFilter$Outbound =
  | EventsFilterCondition$Outbound
  | EventsFilterAND$Outbound
  | EventsFilterOR$Outbound;

/** @internal */
export const EventsFilter$outboundSchema: z.ZodType<
  EventsFilter$Outbound,
  z.ZodTypeDef,
  EventsFilter
> = z.union([
  EventsFilterCondition$outboundSchema,
  z.lazy(() => EventsFilterAND$outboundSchema),
  z.lazy(() => EventsFilterOR$outboundSchema),
]);

export function eventsFilterToJSON(eventsFilter: EventsFilter): string {
  return JSON.stringify(EventsFilter$outboundSchema.parse(eventsFilter));
}
export function eventsFilterFromJSON(
  jsonString: string,
): SafeParseResult<EventsFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsFilter' from JSON`,
  );
}
