/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EventsSimpleFieldSelectionField = {
  Id: "id",
  OrganizationId: "organizationId",
  MessageId: "messageId",
  ConversationId: "conversationId",
  CreatedAt: "createdAt",
  ProjectId: "projectId",
  IntegrationId: "integrationId",
  EventType: "eventType",
  Type: "type",
  SearchQuery: "searchQuery",
  Properties: "properties",
  UserProperties: "userProperties",
} as const;
export type EventsSimpleFieldSelectionField = ClosedEnum<
  typeof EventsSimpleFieldSelectionField
>;

export type EventsSimpleFieldSelection = {
  type: "field";
  field: EventsSimpleFieldSelectionField;
  path?: Array<string> | undefined;
};

/** @internal */
export const EventsSimpleFieldSelectionField$inboundSchema: z.ZodNativeEnum<
  typeof EventsSimpleFieldSelectionField
> = z.nativeEnum(EventsSimpleFieldSelectionField);
/** @internal */
export const EventsSimpleFieldSelectionField$outboundSchema: z.ZodNativeEnum<
  typeof EventsSimpleFieldSelectionField
> = EventsSimpleFieldSelectionField$inboundSchema;

/** @internal */
export const EventsSimpleFieldSelection$inboundSchema: z.ZodType<
  EventsSimpleFieldSelection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("field"),
  field: EventsSimpleFieldSelectionField$inboundSchema,
  path: z.array(z.string()).optional(),
});
/** @internal */
export type EventsSimpleFieldSelection$Outbound = {
  type: "field";
  field: string;
  path?: Array<string> | undefined;
};

/** @internal */
export const EventsSimpleFieldSelection$outboundSchema: z.ZodType<
  EventsSimpleFieldSelection$Outbound,
  z.ZodTypeDef,
  EventsSimpleFieldSelection
> = z.object({
  type: z.literal("field"),
  field: EventsSimpleFieldSelectionField$outboundSchema,
  path: z.array(z.string()).optional(),
});

export function eventsSimpleFieldSelectionToJSON(
  eventsSimpleFieldSelection: EventsSimpleFieldSelection,
): string {
  return JSON.stringify(
    EventsSimpleFieldSelection$outboundSchema.parse(eventsSimpleFieldSelection),
  );
}
export function eventsSimpleFieldSelectionFromJSON(
  jsonString: string,
): SafeParseResult<EventsSimpleFieldSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsSimpleFieldSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsSimpleFieldSelection' from JSON`,
  );
}
