/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FeedbackFilter,
  FeedbackFilter$inboundSchema,
  FeedbackFilter$Outbound,
  FeedbackFilter$outboundSchema,
} from "./feedbackfilter.js";

/**
 * FeedbackFilter OR operator
 */
export type FeedbackFilterOR = {
  /**
   * FeedbackFilter OR condition
   */
  or: Array<FeedbackFilter>;
};

export type FeedbackFilterOROR = FeedbackFilter;

/** @internal */
export const FeedbackFilterOR$inboundSchema: z.ZodType<
  FeedbackFilterOR,
  z.ZodTypeDef,
  unknown
> = z.object({
  or: z.array(z.lazy(() => FeedbackFilter$inboundSchema)),
});
/** @internal */
export type FeedbackFilterOR$Outbound = {
  or: Array<FeedbackFilter$Outbound>;
};

/** @internal */
export const FeedbackFilterOR$outboundSchema: z.ZodType<
  FeedbackFilterOR$Outbound,
  z.ZodTypeDef,
  FeedbackFilterOR
> = z.object({
  or: z.array(z.lazy(() => FeedbackFilter$outboundSchema)),
});

export function feedbackFilterORToJSON(
  feedbackFilterOR: FeedbackFilterOR,
): string {
  return JSON.stringify(
    FeedbackFilterOR$outboundSchema.parse(feedbackFilterOR),
  );
}
export function feedbackFilterORFromJSON(
  jsonString: string,
): SafeParseResult<FeedbackFilterOR, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeedbackFilterOR$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeedbackFilterOR' from JSON`,
  );
}

/** @internal */
export const FeedbackFilterOROR$inboundSchema: z.ZodType<
  FeedbackFilterOROR,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => FeedbackFilter$inboundSchema);
/** @internal */
export type FeedbackFilterOROR$Outbound = FeedbackFilter$Outbound;

/** @internal */
export const FeedbackFilterOROR$outboundSchema: z.ZodType<
  FeedbackFilterOROR$Outbound,
  z.ZodTypeDef,
  FeedbackFilterOROR
> = z.lazy(() => FeedbackFilter$outboundSchema);

export function feedbackFilterORORToJSON(
  feedbackFilterOROR: FeedbackFilterOROR,
): string {
  return JSON.stringify(
    FeedbackFilterOROR$outboundSchema.parse(feedbackFilterOROR),
  );
}
export function feedbackFilterORORFromJSON(
  jsonString: string,
): SafeParseResult<FeedbackFilterOROR, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeedbackFilterOROR$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeedbackFilterOROR' from JSON`,
  );
}
