/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Available fields for Feedback
 */
export const FeedbackField = {
  Id: "id",
  Type: "type",
  MessageId: "messageId",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  OrganizationId: "organizationId",
  Reasons: "reasons",
  Sources: "sources",
  Details: "details",
  Properties: "properties",
  UserProperties: "userProperties",
  ConversationId: "conversationId",
  ProjectId: "projectId",
  IntegrationId: "integrationId",
} as const;
/**
 * Available fields for Feedback
 */
export type FeedbackField = ClosedEnum<typeof FeedbackField>;

/** @internal */
export const FeedbackField$inboundSchema: z.ZodNativeEnum<
  typeof FeedbackField
> = z.nativeEnum(FeedbackField);
/** @internal */
export const FeedbackField$outboundSchema: z.ZodNativeEnum<
  typeof FeedbackField
> = FeedbackField$inboundSchema;
