/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FeedbackSimpleFieldSelectionField = {
  Id: "id",
  Type: "type",
  MessageId: "messageId",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  OrganizationId: "organizationId",
  Reasons: "reasons",
  Sources: "sources",
  Details: "details",
  Properties: "properties",
  UserProperties: "userProperties",
  ConversationId: "conversationId",
  ProjectId: "projectId",
  IntegrationId: "integrationId",
} as const;
export type FeedbackSimpleFieldSelectionField = ClosedEnum<
  typeof FeedbackSimpleFieldSelectionField
>;

export type FeedbackSimpleFieldSelection = {
  type: "field";
  field: FeedbackSimpleFieldSelectionField;
  path?: Array<string> | undefined;
};

/** @internal */
export const FeedbackSimpleFieldSelectionField$inboundSchema: z.ZodNativeEnum<
  typeof FeedbackSimpleFieldSelectionField
> = z.nativeEnum(FeedbackSimpleFieldSelectionField);
/** @internal */
export const FeedbackSimpleFieldSelectionField$outboundSchema: z.ZodNativeEnum<
  typeof FeedbackSimpleFieldSelectionField
> = FeedbackSimpleFieldSelectionField$inboundSchema;

/** @internal */
export const FeedbackSimpleFieldSelection$inboundSchema: z.ZodType<
  FeedbackSimpleFieldSelection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("field"),
  field: FeedbackSimpleFieldSelectionField$inboundSchema,
  path: z.array(z.string()).optional(),
});
/** @internal */
export type FeedbackSimpleFieldSelection$Outbound = {
  type: "field";
  field: string;
  path?: Array<string> | undefined;
};

/** @internal */
export const FeedbackSimpleFieldSelection$outboundSchema: z.ZodType<
  FeedbackSimpleFieldSelection$Outbound,
  z.ZodTypeDef,
  FeedbackSimpleFieldSelection
> = z.object({
  type: z.literal("field"),
  field: FeedbackSimpleFieldSelectionField$outboundSchema,
  path: z.array(z.string()).optional(),
});

export function feedbackSimpleFieldSelectionToJSON(
  feedbackSimpleFieldSelection: FeedbackSimpleFieldSelection,
): string {
  return JSON.stringify(
    FeedbackSimpleFieldSelection$outboundSchema.parse(
      feedbackSimpleFieldSelection,
    ),
  );
}
export function feedbackSimpleFieldSelectionFromJSON(
  jsonString: string,
): SafeParseResult<FeedbackSimpleFieldSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeedbackSimpleFieldSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeedbackSimpleFieldSelection' from JSON`,
  );
}
