/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Available operators for filtering data
 */
export const FilterOperator = {
  Eq: "eq",
  Neq: "neq",
  Gt: "gt",
  Gte: "gte",
  Lt: "lt",
  Lte: "lte",
  In: "in",
  NotIn: "notIn",
  ArrayContains: "arrayContains",
  JsonContains: "jsonContains",
  JsonContainedBy: "jsonContainedBy",
  JsonHasKey: "jsonHasKey",
  JsonArrayContainsObject: "jsonArrayContainsObject",
  JsonHasAnyKey: "jsonHasAnyKey",
  JsonHasAllKeys: "jsonHasAllKeys",
  IsNull: "isNull",
  IsNotNull: "isNotNull",
} as const;
/**
 * Available operators for filtering data
 */
export type FilterOperator = ClosedEnum<typeof FilterOperator>;

/** @internal */
export const FilterOperator$inboundSchema: z.ZodNativeEnum<
  typeof FilterOperator
> = z.nativeEnum(FilterOperator);
/** @internal */
export const FilterOperator$outboundSchema: z.ZodNativeEnum<
  typeof FilterOperator
> = FilterOperator$inboundSchema;
