/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The unique identifier for the user. This value is sent by the inkeep widget.
 */
export type InsertSearchEventId = string | number;

/**
 * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
 */
export type InsertSearchEventUserId = string | number;

/**
 * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
 */
export type InsertSearchEventUserProperties = {
  /**
   * The unique identifier for the user. This value is sent by the inkeep widget.
   */
  id?: string | number | null | undefined;
  /**
   * The type of identification for the user. This value is sent by the inkeep widget.
   */
  identificationType?: string | null | undefined;
  /**
   * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userId?: string | number | null | undefined;
  /**
   * The name of the support agent assigned to the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  supportAgentName?: string | null | undefined;
  /**
   * The email of the support agent assigned to the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  supportAgentEmail?: string | null | undefined;
  /**
   * The type of user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userType?: string | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type InsertSearchEvent = {
  id?: string | undefined;
  type: string;
  searchQuery: string;
  /**
   * A timestamp in ISO 8601 format with timezone information. If not provided, the current time will be used.
   */
  createdAt?: Date | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  /**
   * A customizable collection of custom properties or attributes.
   */
  properties?: { [k: string]: any } | null | undefined;
  /**
   * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
   */
  userProperties?: InsertSearchEventUserProperties | null | undefined;
  entityType: "search";
};

/** @internal */
export const InsertSearchEventId$inboundSchema: z.ZodType<
  InsertSearchEventId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type InsertSearchEventId$Outbound = string | number;

/** @internal */
export const InsertSearchEventId$outboundSchema: z.ZodType<
  InsertSearchEventId$Outbound,
  z.ZodTypeDef,
  InsertSearchEventId
> = z.union([z.string(), z.number()]);

export function insertSearchEventIdToJSON(
  insertSearchEventId: InsertSearchEventId,
): string {
  return JSON.stringify(
    InsertSearchEventId$outboundSchema.parse(insertSearchEventId),
  );
}
export function insertSearchEventIdFromJSON(
  jsonString: string,
): SafeParseResult<InsertSearchEventId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertSearchEventId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertSearchEventId' from JSON`,
  );
}

/** @internal */
export const InsertSearchEventUserId$inboundSchema: z.ZodType<
  InsertSearchEventUserId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type InsertSearchEventUserId$Outbound = string | number;

/** @internal */
export const InsertSearchEventUserId$outboundSchema: z.ZodType<
  InsertSearchEventUserId$Outbound,
  z.ZodTypeDef,
  InsertSearchEventUserId
> = z.union([z.string(), z.number()]);

export function insertSearchEventUserIdToJSON(
  insertSearchEventUserId: InsertSearchEventUserId,
): string {
  return JSON.stringify(
    InsertSearchEventUserId$outboundSchema.parse(insertSearchEventUserId),
  );
}
export function insertSearchEventUserIdFromJSON(
  jsonString: string,
): SafeParseResult<InsertSearchEventUserId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertSearchEventUserId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertSearchEventUserId' from JSON`,
  );
}

/** @internal */
export const InsertSearchEventUserProperties$inboundSchema: z.ZodType<
  InsertSearchEventUserProperties,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.nullable(z.union([z.string(), z.number()])).optional(),
    identificationType: z.nullable(z.string()).optional(),
    userId: z.nullable(z.union([z.string(), z.number()])).optional(),
    supportAgentName: z.nullable(z.string()).optional(),
    supportAgentEmail: z.nullable(z.string()).optional(),
    userType: z.nullable(z.string()).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type InsertSearchEventUserProperties$Outbound = {
  id?: string | number | null | undefined;
  identificationType?: string | null | undefined;
  userId?: string | number | null | undefined;
  supportAgentName?: string | null | undefined;
  supportAgentEmail?: string | null | undefined;
  userType?: string | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const InsertSearchEventUserProperties$outboundSchema: z.ZodType<
  InsertSearchEventUserProperties$Outbound,
  z.ZodTypeDef,
  InsertSearchEventUserProperties
> = z.object({
  id: z.nullable(z.union([z.string(), z.number()])).optional(),
  identificationType: z.nullable(z.string()).optional(),
  userId: z.nullable(z.union([z.string(), z.number()])).optional(),
  supportAgentName: z.nullable(z.string()).optional(),
  supportAgentEmail: z.nullable(z.string()).optional(),
  userType: z.nullable(z.string()).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function insertSearchEventUserPropertiesToJSON(
  insertSearchEventUserProperties: InsertSearchEventUserProperties,
): string {
  return JSON.stringify(
    InsertSearchEventUserProperties$outboundSchema.parse(
      insertSearchEventUserProperties,
    ),
  );
}
export function insertSearchEventUserPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<InsertSearchEventUserProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertSearchEventUserProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertSearchEventUserProperties' from JSON`,
  );
}

/** @internal */
export const InsertSearchEvent$inboundSchema: z.ZodType<
  InsertSearchEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  searchQuery: z.string(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => InsertSearchEventUserProperties$inboundSchema),
  ).optional(),
  entityType: z.literal("search"),
});
/** @internal */
export type InsertSearchEvent$Outbound = {
  id?: string | undefined;
  type: string;
  searchQuery: string;
  createdAt?: string | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  properties?: { [k: string]: any } | null | undefined;
  userProperties?: InsertSearchEventUserProperties$Outbound | null | undefined;
  entityType: "search";
};

/** @internal */
export const InsertSearchEvent$outboundSchema: z.ZodType<
  InsertSearchEvent$Outbound,
  z.ZodTypeDef,
  InsertSearchEvent
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  searchQuery: z.string(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => InsertSearchEventUserProperties$outboundSchema),
  ).optional(),
  entityType: z.literal("search"),
});

export function insertSearchEventToJSON(
  insertSearchEvent: InsertSearchEvent,
): string {
  return JSON.stringify(
    InsertSearchEvent$outboundSchema.parse(insertSearchEvent),
  );
}
export function insertSearchEventFromJSON(
  jsonString: string,
): SafeParseResult<InsertSearchEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertSearchEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertSearchEvent' from JSON`,
  );
}
