/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InsertConversationEventProperties = {};

export type InsertConversationEventUserProperties = {};

export const InsertConversationEventEntityType = {
  Conversation: "conversation",
} as const;
export type InsertConversationEventEntityType = ClosedEnum<
  typeof InsertConversationEventEntityType
>;

export type InsertConversationEvent = {
  id?: string | undefined;
  type: string;
  conversationId: string;
  createdAt?: Date | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  properties?: InsertConversationEventProperties | null | undefined;
  userProperties?: InsertConversationEventUserProperties | null | undefined;
  entityType: InsertConversationEventEntityType;
};

/** @internal */
export const InsertConversationEventProperties$inboundSchema: z.ZodType<
  InsertConversationEventProperties,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type InsertConversationEventProperties$Outbound = {};

/** @internal */
export const InsertConversationEventProperties$outboundSchema: z.ZodType<
  InsertConversationEventProperties$Outbound,
  z.ZodTypeDef,
  InsertConversationEventProperties
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertConversationEventProperties$ {
  /** @deprecated use `InsertConversationEventProperties$inboundSchema` instead. */
  export const inboundSchema = InsertConversationEventProperties$inboundSchema;
  /** @deprecated use `InsertConversationEventProperties$outboundSchema` instead. */
  export const outboundSchema =
    InsertConversationEventProperties$outboundSchema;
  /** @deprecated use `InsertConversationEventProperties$Outbound` instead. */
  export type Outbound = InsertConversationEventProperties$Outbound;
}

export function insertConversationEventPropertiesToJSON(
  insertConversationEventProperties: InsertConversationEventProperties,
): string {
  return JSON.stringify(
    InsertConversationEventProperties$outboundSchema.parse(
      insertConversationEventProperties,
    ),
  );
}

export function insertConversationEventPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<InsertConversationEventProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertConversationEventProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertConversationEventProperties' from JSON`,
  );
}

/** @internal */
export const InsertConversationEventUserProperties$inboundSchema: z.ZodType<
  InsertConversationEventUserProperties,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type InsertConversationEventUserProperties$Outbound = {};

/** @internal */
export const InsertConversationEventUserProperties$outboundSchema: z.ZodType<
  InsertConversationEventUserProperties$Outbound,
  z.ZodTypeDef,
  InsertConversationEventUserProperties
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertConversationEventUserProperties$ {
  /** @deprecated use `InsertConversationEventUserProperties$inboundSchema` instead. */
  export const inboundSchema =
    InsertConversationEventUserProperties$inboundSchema;
  /** @deprecated use `InsertConversationEventUserProperties$outboundSchema` instead. */
  export const outboundSchema =
    InsertConversationEventUserProperties$outboundSchema;
  /** @deprecated use `InsertConversationEventUserProperties$Outbound` instead. */
  export type Outbound = InsertConversationEventUserProperties$Outbound;
}

export function insertConversationEventUserPropertiesToJSON(
  insertConversationEventUserProperties: InsertConversationEventUserProperties,
): string {
  return JSON.stringify(
    InsertConversationEventUserProperties$outboundSchema.parse(
      insertConversationEventUserProperties,
    ),
  );
}

export function insertConversationEventUserPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<InsertConversationEventUserProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InsertConversationEventUserProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertConversationEventUserProperties' from JSON`,
  );
}

/** @internal */
export const InsertConversationEventEntityType$inboundSchema: z.ZodNativeEnum<
  typeof InsertConversationEventEntityType
> = z.nativeEnum(InsertConversationEventEntityType);

/** @internal */
export const InsertConversationEventEntityType$outboundSchema: z.ZodNativeEnum<
  typeof InsertConversationEventEntityType
> = InsertConversationEventEntityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertConversationEventEntityType$ {
  /** @deprecated use `InsertConversationEventEntityType$inboundSchema` instead. */
  export const inboundSchema = InsertConversationEventEntityType$inboundSchema;
  /** @deprecated use `InsertConversationEventEntityType$outboundSchema` instead. */
  export const outboundSchema =
    InsertConversationEventEntityType$outboundSchema;
}

/** @internal */
export const InsertConversationEvent$inboundSchema: z.ZodType<
  InsertConversationEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  conversationId: z.string(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(
    z.lazy(() => InsertConversationEventProperties$inboundSchema),
  ).optional(),
  userProperties: z.nullable(
    z.lazy(() => InsertConversationEventUserProperties$inboundSchema),
  ).optional(),
  entityType: InsertConversationEventEntityType$inboundSchema,
});

/** @internal */
export type InsertConversationEvent$Outbound = {
  id?: string | undefined;
  type: string;
  conversationId: string;
  createdAt?: string | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  properties?: InsertConversationEventProperties$Outbound | null | undefined;
  userProperties?:
    | InsertConversationEventUserProperties$Outbound
    | null
    | undefined;
  entityType: string;
};

/** @internal */
export const InsertConversationEvent$outboundSchema: z.ZodType<
  InsertConversationEvent$Outbound,
  z.ZodTypeDef,
  InsertConversationEvent
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  conversationId: z.string(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(
    z.lazy(() => InsertConversationEventProperties$outboundSchema),
  ).optional(),
  userProperties: z.nullable(
    z.lazy(() => InsertConversationEventUserProperties$outboundSchema),
  ).optional(),
  entityType: InsertConversationEventEntityType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertConversationEvent$ {
  /** @deprecated use `InsertConversationEvent$inboundSchema` instead. */
  export const inboundSchema = InsertConversationEvent$inboundSchema;
  /** @deprecated use `InsertConversationEvent$outboundSchema` instead. */
  export const outboundSchema = InsertConversationEvent$outboundSchema;
  /** @deprecated use `InsertConversationEvent$Outbound` instead. */
  export type Outbound = InsertConversationEvent$Outbound;
}

export function insertConversationEventToJSON(
  insertConversationEvent: InsertConversationEvent,
): string {
  return JSON.stringify(
    InsertConversationEvent$outboundSchema.parse(insertConversationEvent),
  );
}

export function insertConversationEventFromJSON(
  jsonString: string,
): SafeParseResult<InsertConversationEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertConversationEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertConversationEvent' from JSON`,
  );
}
