/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EntityType = {
  Message: "message",
} as const;
export type EntityType = ClosedEnum<typeof EntityType>;

export type InsertMessageEvent = {
  id?: string | undefined;
  type: string;
  messageId: string;
  /**
   * A timestamp in ISO 8601 format with timezone information. If not provided, the current time will be used.
   */
  createdAt?: Date | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  /**
   * A customizable collection of custom properties or attributes.
   */
  properties?: { [k: string]: any } | null | undefined;
  /**
   * A customizable collection of custom properties or attributes.
   */
  userProperties?: { [k: string]: any } | null | undefined;
  entityType: EntityType;
};

/** @internal */
export const EntityType$inboundSchema: z.ZodNativeEnum<typeof EntityType> = z
  .nativeEnum(EntityType);

/** @internal */
export const EntityType$outboundSchema: z.ZodNativeEnum<typeof EntityType> =
  EntityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EntityType$ {
  /** @deprecated use `EntityType$inboundSchema` instead. */
  export const inboundSchema = EntityType$inboundSchema;
  /** @deprecated use `EntityType$outboundSchema` instead. */
  export const outboundSchema = EntityType$outboundSchema;
}

/** @internal */
export const InsertMessageEvent$inboundSchema: z.ZodType<
  InsertMessageEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  messageId: z.string(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(z.record(z.any())).optional(),
  entityType: EntityType$inboundSchema,
});

/** @internal */
export type InsertMessageEvent$Outbound = {
  id?: string | undefined;
  type: string;
  messageId: string;
  createdAt?: string | null | undefined;
  projectId?: string | null | undefined;
  integrationId?: string | null | undefined;
  properties?: { [k: string]: any } | null | undefined;
  userProperties?: { [k: string]: any } | null | undefined;
  entityType: string;
};

/** @internal */
export const InsertMessageEvent$outboundSchema: z.ZodType<
  InsertMessageEvent$Outbound,
  z.ZodTypeDef,
  InsertMessageEvent
> = z.object({
  id: z.string().optional(),
  type: z.string(),
  messageId: z.string(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  projectId: z.nullable(z.string()).optional(),
  integrationId: z.nullable(z.string()).optional(),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(z.record(z.any())).optional(),
  entityType: EntityType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertMessageEvent$ {
  /** @deprecated use `InsertMessageEvent$inboundSchema` instead. */
  export const inboundSchema = InsertMessageEvent$inboundSchema;
  /** @deprecated use `InsertMessageEvent$outboundSchema` instead. */
  export const outboundSchema = InsertMessageEvent$outboundSchema;
  /** @deprecated use `InsertMessageEvent$Outbound` instead. */
  export type Outbound = InsertMessageEvent$Outbound;
}

export function insertMessageEventToJSON(
  insertMessageEvent: InsertMessageEvent,
): string {
  return JSON.stringify(
    InsertMessageEvent$outboundSchema.parse(insertMessageEvent),
  );
}

export function insertMessageEventFromJSON(
  jsonString: string,
): SafeParseResult<InsertMessageEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsertMessageEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsertMessageEvent' from JSON`,
  );
}
