/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Which JSON field to query values from
 */
export const PropertyValuesRequestBodyField = {
  Properties: "properties",
  UserProperties: "userProperties",
} as const;
/**
 * Which JSON field to query values from
 */
export type PropertyValuesRequestBodyField = ClosedEnum<
  typeof PropertyValuesRequestBodyField
>;

export const PropertyValuesRequestBodyViews = {
  EventsView: "events_view",
  ConversationsView: "conversations_view",
  SemanticThreadsView: "semantic_threads_view",
  FeedbackView: "feedback_view",
} as const;
export type PropertyValuesRequestBodyViews = ClosedEnum<
  typeof PropertyValuesRequestBodyViews
>;

/**
 * Query Property Values Params
 */
export type PropertyValuesRequestBody = {
  /**
   * Which JSON field to query values from
   */
  field: PropertyValuesRequestBodyField;
  /**
   * The property key to get values for
   */
  key: string;
  /**
   * Optional list of views to query (defaults to all views)
   */
  views?: Array<PropertyValuesRequestBodyViews> | undefined;
  /**
   * Maximum number of values to return
   */
  limit?: number | undefined;
};

/** @internal */
export const PropertyValuesRequestBodyField$inboundSchema: z.ZodNativeEnum<
  typeof PropertyValuesRequestBodyField
> = z.nativeEnum(PropertyValuesRequestBodyField);
/** @internal */
export const PropertyValuesRequestBodyField$outboundSchema: z.ZodNativeEnum<
  typeof PropertyValuesRequestBodyField
> = PropertyValuesRequestBodyField$inboundSchema;

/** @internal */
export const PropertyValuesRequestBodyViews$inboundSchema: z.ZodNativeEnum<
  typeof PropertyValuesRequestBodyViews
> = z.nativeEnum(PropertyValuesRequestBodyViews);
/** @internal */
export const PropertyValuesRequestBodyViews$outboundSchema: z.ZodNativeEnum<
  typeof PropertyValuesRequestBodyViews
> = PropertyValuesRequestBodyViews$inboundSchema;

/** @internal */
export const PropertyValuesRequestBody$inboundSchema: z.ZodType<
  PropertyValuesRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  field: PropertyValuesRequestBodyField$inboundSchema,
  key: z.string(),
  views: z.array(PropertyValuesRequestBodyViews$inboundSchema).optional(),
  limit: z.number().default(100),
});
/** @internal */
export type PropertyValuesRequestBody$Outbound = {
  field: string;
  key: string;
  views?: Array<string> | undefined;
  limit: number;
};

/** @internal */
export const PropertyValuesRequestBody$outboundSchema: z.ZodType<
  PropertyValuesRequestBody$Outbound,
  z.ZodTypeDef,
  PropertyValuesRequestBody
> = z.object({
  field: PropertyValuesRequestBodyField$outboundSchema,
  key: z.string(),
  views: z.array(PropertyValuesRequestBodyViews$outboundSchema).optional(),
  limit: z.number().default(100),
});

export function propertyValuesRequestBodyToJSON(
  propertyValuesRequestBody: PropertyValuesRequestBody,
): string {
  return JSON.stringify(
    PropertyValuesRequestBody$outboundSchema.parse(propertyValuesRequestBody),
  );
}
export function propertyValuesRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PropertyValuesRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PropertyValuesRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PropertyValuesRequestBody' from JSON`,
  );
}
