/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PropertyValuesResponseBody = {
  results: Array<string>;
};

/** @internal */
export const PropertyValuesResponseBody$inboundSchema: z.ZodType<
  PropertyValuesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(z.string()),
});
/** @internal */
export type PropertyValuesResponseBody$Outbound = {
  results: Array<string>;
};

/** @internal */
export const PropertyValuesResponseBody$outboundSchema: z.ZodType<
  PropertyValuesResponseBody$Outbound,
  z.ZodTypeDef,
  PropertyValuesResponseBody
> = z.object({
  results: z.array(z.string()),
});

export function propertyValuesResponseBodyToJSON(
  propertyValuesResponseBody: PropertyValuesResponseBody,
): string {
  return JSON.stringify(
    PropertyValuesResponseBody$outboundSchema.parse(propertyValuesResponseBody),
  );
}
export function propertyValuesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PropertyValuesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PropertyValuesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PropertyValuesResponseBody' from JSON`,
  );
}
