/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PropertyKeysResponseBody = {
  results: Array<string>;
};

/** @internal */
export const PropertyKeysResponseBody$inboundSchema: z.ZodType<
  PropertyKeysResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(z.string()),
});
/** @internal */
export type PropertyKeysResponseBody$Outbound = {
  results: Array<string>;
};

/** @internal */
export const PropertyKeysResponseBody$outboundSchema: z.ZodType<
  PropertyKeysResponseBody$Outbound,
  z.ZodTypeDef,
  PropertyKeysResponseBody
> = z.object({
  results: z.array(z.string()),
});

export function propertyKeysResponseBodyToJSON(
  propertyKeysResponseBody: PropertyKeysResponseBody,
): string {
  return JSON.stringify(
    PropertyKeysResponseBody$outboundSchema.parse(propertyKeysResponseBody),
  );
}
export function propertyKeysResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PropertyKeysResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PropertyKeysResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PropertyKeysResponseBody' from JSON`,
  );
}
