/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QueryEventsResponseData,
  QueryEventsResponseData$inboundSchema,
  QueryEventsResponseData$Outbound,
  QueryEventsResponseData$outboundSchema,
} from "./queryeventsresponsedata.js";

/**
 * Status of the response
 */
export const QueryEventsResponseBodyStatus = {
  Ok: "ok",
} as const;
/**
 * Status of the response
 */
export type QueryEventsResponseBodyStatus = ClosedEnum<
  typeof QueryEventsResponseBodyStatus
>;

/**
 * Response body for QueryEvents query endpoint
 */
export type QueryEventsResponseBody = {
  /**
   * Status of the response
   */
  status: QueryEventsResponseBodyStatus;
  /**
   * Data object containing QueryEvents query results and pagination information
   */
  data: QueryEventsResponseData;
};

/** @internal */
export const QueryEventsResponseBodyStatus$inboundSchema: z.ZodNativeEnum<
  typeof QueryEventsResponseBodyStatus
> = z.nativeEnum(QueryEventsResponseBodyStatus);
/** @internal */
export const QueryEventsResponseBodyStatus$outboundSchema: z.ZodNativeEnum<
  typeof QueryEventsResponseBodyStatus
> = QueryEventsResponseBodyStatus$inboundSchema;

/** @internal */
export const QueryEventsResponseBody$inboundSchema: z.ZodType<
  QueryEventsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: QueryEventsResponseBodyStatus$inboundSchema,
  data: QueryEventsResponseData$inboundSchema,
});
/** @internal */
export type QueryEventsResponseBody$Outbound = {
  status: string;
  data: QueryEventsResponseData$Outbound;
};

/** @internal */
export const QueryEventsResponseBody$outboundSchema: z.ZodType<
  QueryEventsResponseBody$Outbound,
  z.ZodTypeDef,
  QueryEventsResponseBody
> = z.object({
  status: QueryEventsResponseBodyStatus$outboundSchema,
  data: QueryEventsResponseData$outboundSchema,
});

export function queryEventsResponseBodyToJSON(
  queryEventsResponseBody: QueryEventsResponseBody,
): string {
  return JSON.stringify(
    QueryEventsResponseBody$outboundSchema.parse(queryEventsResponseBody),
  );
}
export function queryEventsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueryEventsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEventsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEventsResponseBody' from JSON`,
  );
}
