/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SelectSearchEventEntityType = {
  Search: "search",
} as const;
export type SelectSearchEventEntityType = ClosedEnum<
  typeof SelectSearchEventEntityType
>;

export type SelectSearchEvent = {
  id: string;
  type: string;
  searchQuery: string;
  createdAt: string;
  projectId: string | null;
  integrationId: string | null;
  /**
   * A customizable collection of custom properties or attributes.
   */
  properties?: { [k: string]: any } | null | undefined;
  /**
   * A customizable collection of custom properties or attributes.
   */
  userProperties?: { [k: string]: any } | null | undefined;
  entityType: SelectSearchEventEntityType;
};

/** @internal */
export const SelectSearchEventEntityType$inboundSchema: z.ZodNativeEnum<
  typeof SelectSearchEventEntityType
> = z.nativeEnum(SelectSearchEventEntityType);

/** @internal */
export const SelectSearchEventEntityType$outboundSchema: z.ZodNativeEnum<
  typeof SelectSearchEventEntityType
> = SelectSearchEventEntityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelectSearchEventEntityType$ {
  /** @deprecated use `SelectSearchEventEntityType$inboundSchema` instead. */
  export const inboundSchema = SelectSearchEventEntityType$inboundSchema;
  /** @deprecated use `SelectSearchEventEntityType$outboundSchema` instead. */
  export const outboundSchema = SelectSearchEventEntityType$outboundSchema;
}

/** @internal */
export const SelectSearchEvent$inboundSchema: z.ZodType<
  SelectSearchEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
  searchQuery: z.string(),
  createdAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(z.record(z.any())).optional(),
  entityType: SelectSearchEventEntityType$inboundSchema,
});

/** @internal */
export type SelectSearchEvent$Outbound = {
  id: string;
  type: string;
  searchQuery: string;
  createdAt: string;
  projectId: string | null;
  integrationId: string | null;
  properties?: { [k: string]: any } | null | undefined;
  userProperties?: { [k: string]: any } | null | undefined;
  entityType: string;
};

/** @internal */
export const SelectSearchEvent$outboundSchema: z.ZodType<
  SelectSearchEvent$Outbound,
  z.ZodTypeDef,
  SelectSearchEvent
> = z.object({
  id: z.string(),
  type: z.string(),
  searchQuery: z.string(),
  createdAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(z.record(z.any())).optional(),
  entityType: SelectSearchEventEntityType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelectSearchEvent$ {
  /** @deprecated use `SelectSearchEvent$inboundSchema` instead. */
  export const inboundSchema = SelectSearchEvent$inboundSchema;
  /** @deprecated use `SelectSearchEvent$outboundSchema` instead. */
  export const outboundSchema = SelectSearchEvent$outboundSchema;
  /** @deprecated use `SelectSearchEvent$Outbound` instead. */
  export type Outbound = SelectSearchEvent$Outbound;
}

export function selectSearchEventToJSON(
  selectSearchEvent: SelectSearchEvent,
): string {
  return JSON.stringify(
    SelectSearchEvent$outboundSchema.parse(selectSearchEvent),
  );
}

export function selectSearchEventFromJSON(
  jsonString: string,
): SafeParseResult<SelectSearchEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectSearchEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectSearchEvent' from JSON`,
  );
}
