/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SemanticThreadAggregationSelectionAggregation = {
  Sum: "sum",
  Count: "count",
  CountDistinct: "countDistinct",
  Avg: "avg",
  Min: "min",
  Max: "max",
} as const;
export type SemanticThreadAggregationSelectionAggregation = ClosedEnum<
  typeof SemanticThreadAggregationSelectionAggregation
>;

export const SemanticThreadAggregationSelectionField = {
  Id: "id",
  MessageIds: "messageIds",
  MessagesCount: "messagesCount",
  OrganizationId: "organizationId",
  Question: "question",
  QuestionLength: "questionLength",
  Answer: "answer",
  IsOnTopic: "isOnTopic",
  IsClear: "isClear",
  IsDocumented: "isDocumented",
  IsFeatureSupported: "isFeatureSupported",
  IsAnswerConfident: "isAnswerConfident",
  GapSummary: "gapSummary",
  Subject: "subject",
  Category: "category",
  Languages: "languages",
  FirstPartyEntities: "firstPartyEntities",
  ThirdPartyEntities: "thirdPartyEntities",
  Emotion: "emotion",
  Sentiment: "sentiment",
  QuestionType: "questionType",
  ProjectId: "projectId",
  IntegrationId: "integrationId",
  Properties: "properties",
  UserProperties: "userProperties",
  FirstMessageTime: "firstMessageTime",
  LastMessageTime: "lastMessageTime",
  LastUpdated: "lastUpdated",
  HasPositiveFeedback: "hasPositiveFeedback",
  HasNegativeFeedback: "hasNegativeFeedback",
  ConversationIds: "conversationIds",
  AreAIAnnotationsVerified: "areAIAnnotationsVerified",
  IsInitialQuestionAnswer: "isInitialQuestionAnswer",
} as const;
export type SemanticThreadAggregationSelectionField = ClosedEnum<
  typeof SemanticThreadAggregationSelectionField
>;

export type SemanticThreadAggregationSelection = {
  type: "aggregation";
  aggregation: SemanticThreadAggregationSelectionAggregation;
  field?: SemanticThreadAggregationSelectionField | undefined;
  path?: Array<string> | undefined;
};

/** @internal */
export const SemanticThreadAggregationSelectionAggregation$inboundSchema:
  z.ZodNativeEnum<typeof SemanticThreadAggregationSelectionAggregation> = z
    .nativeEnum(SemanticThreadAggregationSelectionAggregation);
/** @internal */
export const SemanticThreadAggregationSelectionAggregation$outboundSchema:
  z.ZodNativeEnum<typeof SemanticThreadAggregationSelectionAggregation> =
    SemanticThreadAggregationSelectionAggregation$inboundSchema;

/** @internal */
export const SemanticThreadAggregationSelectionField$inboundSchema:
  z.ZodNativeEnum<typeof SemanticThreadAggregationSelectionField> = z
    .nativeEnum(SemanticThreadAggregationSelectionField);
/** @internal */
export const SemanticThreadAggregationSelectionField$outboundSchema:
  z.ZodNativeEnum<typeof SemanticThreadAggregationSelectionField> =
    SemanticThreadAggregationSelectionField$inboundSchema;

/** @internal */
export const SemanticThreadAggregationSelection$inboundSchema: z.ZodType<
  SemanticThreadAggregationSelection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("aggregation"),
  aggregation: SemanticThreadAggregationSelectionAggregation$inboundSchema,
  field: SemanticThreadAggregationSelectionField$inboundSchema.optional(),
  path: z.array(z.string()).optional(),
});
/** @internal */
export type SemanticThreadAggregationSelection$Outbound = {
  type: "aggregation";
  aggregation: string;
  field?: string | undefined;
  path?: Array<string> | undefined;
};

/** @internal */
export const SemanticThreadAggregationSelection$outboundSchema: z.ZodType<
  SemanticThreadAggregationSelection$Outbound,
  z.ZodTypeDef,
  SemanticThreadAggregationSelection
> = z.object({
  type: z.literal("aggregation"),
  aggregation: SemanticThreadAggregationSelectionAggregation$outboundSchema,
  field: SemanticThreadAggregationSelectionField$outboundSchema.optional(),
  path: z.array(z.string()).optional(),
});

export function semanticThreadAggregationSelectionToJSON(
  semanticThreadAggregationSelection: SemanticThreadAggregationSelection,
): string {
  return JSON.stringify(
    SemanticThreadAggregationSelection$outboundSchema.parse(
      semanticThreadAggregationSelection,
    ),
  );
}
export function semanticThreadAggregationSelectionFromJSON(
  jsonString: string,
): SafeParseResult<SemanticThreadAggregationSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SemanticThreadAggregationSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SemanticThreadAggregationSelection' from JSON`,
  );
}
