/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SimpleFieldSelectionType = {
  Field: "field",
} as const;
export type SimpleFieldSelectionType = ClosedEnum<
  typeof SimpleFieldSelectionType
>;

export const SimpleFieldSelectionField31 = {
  IsInitialQuestionAnswer: "isInitialQuestionAnswer",
} as const;
export type SimpleFieldSelectionField31 = ClosedEnum<
  typeof SimpleFieldSelectionField31
>;

export const SimpleFieldSelectionField30 = {
  AreAIAnnotationsVerified: "areAIAnnotationsVerified",
} as const;
export type SimpleFieldSelectionField30 = ClosedEnum<
  typeof SimpleFieldSelectionField30
>;

export const SimpleFieldSelectionField29 = {
  ConversationIds: "conversationIds",
} as const;
export type SimpleFieldSelectionField29 = ClosedEnum<
  typeof SimpleFieldSelectionField29
>;

export const SimpleFieldSelectionField28 = {
  HasNegativeFeedback: "hasNegativeFeedback",
} as const;
export type SimpleFieldSelectionField28 = ClosedEnum<
  typeof SimpleFieldSelectionField28
>;

export const SimpleFieldSelectionField27 = {
  HasPositiveFeedback: "hasPositiveFeedback",
} as const;
export type SimpleFieldSelectionField27 = ClosedEnum<
  typeof SimpleFieldSelectionField27
>;

export const SimpleFieldSelectionField26 = {
  LastUpdated: "lastUpdated",
} as const;
export type SimpleFieldSelectionField26 = ClosedEnum<
  typeof SimpleFieldSelectionField26
>;

export const SimpleFieldSelectionField25 = {
  LastMessageTime: "lastMessageTime",
} as const;
export type SimpleFieldSelectionField25 = ClosedEnum<
  typeof SimpleFieldSelectionField25
>;

export const SimpleFieldSelectionField24 = {
  FirstMessageTime: "firstMessageTime",
} as const;
export type SimpleFieldSelectionField24 = ClosedEnum<
  typeof SimpleFieldSelectionField24
>;

export const SimpleFieldSelectionField23 = {
  IntegrationId: "integrationId",
} as const;
export type SimpleFieldSelectionField23 = ClosedEnum<
  typeof SimpleFieldSelectionField23
>;

export const SimpleFieldSelectionField22 = {
  ProjectId: "projectId",
} as const;
export type SimpleFieldSelectionField22 = ClosedEnum<
  typeof SimpleFieldSelectionField22
>;

export const SimpleFieldSelectionField21 = {
  QuestionType: "questionType",
} as const;
export type SimpleFieldSelectionField21 = ClosedEnum<
  typeof SimpleFieldSelectionField21
>;

export const SimpleFieldSelectionField20 = {
  Sentiment: "sentiment",
} as const;
export type SimpleFieldSelectionField20 = ClosedEnum<
  typeof SimpleFieldSelectionField20
>;

export const SimpleFieldSelectionField19 = {
  Emotion: "emotion",
} as const;
export type SimpleFieldSelectionField19 = ClosedEnum<
  typeof SimpleFieldSelectionField19
>;

export const SimpleFieldSelectionField18 = {
  ThirdPartyEntities: "thirdPartyEntities",
} as const;
export type SimpleFieldSelectionField18 = ClosedEnum<
  typeof SimpleFieldSelectionField18
>;

export const SimpleFieldSelectionField17 = {
  FirstPartyEntities: "firstPartyEntities",
} as const;
export type SimpleFieldSelectionField17 = ClosedEnum<
  typeof SimpleFieldSelectionField17
>;

export const SimpleFieldSelectionField16 = {
  Languages: "languages",
} as const;
export type SimpleFieldSelectionField16 = ClosedEnum<
  typeof SimpleFieldSelectionField16
>;

export const SimpleFieldSelectionField15 = {
  Category: "category",
} as const;
export type SimpleFieldSelectionField15 = ClosedEnum<
  typeof SimpleFieldSelectionField15
>;

export const SimpleFieldSelectionField14 = {
  Subject: "subject",
} as const;
export type SimpleFieldSelectionField14 = ClosedEnum<
  typeof SimpleFieldSelectionField14
>;

export const SimpleFieldSelectionField13 = {
  GapSummary: "gapSummary",
} as const;
export type SimpleFieldSelectionField13 = ClosedEnum<
  typeof SimpleFieldSelectionField13
>;

export const SimpleFieldSelectionField12 = {
  IsAnswerConfident: "isAnswerConfident",
} as const;
export type SimpleFieldSelectionField12 = ClosedEnum<
  typeof SimpleFieldSelectionField12
>;

export const SimpleFieldSelectionField11 = {
  IsFeatureSupported: "isFeatureSupported",
} as const;
export type SimpleFieldSelectionField11 = ClosedEnum<
  typeof SimpleFieldSelectionField11
>;

export const SimpleFieldSelectionField10 = {
  IsDocumented: "isDocumented",
} as const;
export type SimpleFieldSelectionField10 = ClosedEnum<
  typeof SimpleFieldSelectionField10
>;

export const SimpleFieldSelectionField9 = {
  IsClear: "isClear",
} as const;
export type SimpleFieldSelectionField9 = ClosedEnum<
  typeof SimpleFieldSelectionField9
>;

export const SimpleFieldSelectionField8 = {
  IsOnTopic: "isOnTopic",
} as const;
export type SimpleFieldSelectionField8 = ClosedEnum<
  typeof SimpleFieldSelectionField8
>;

export const SimpleFieldSelectionField7 = {
  Answer: "answer",
} as const;
export type SimpleFieldSelectionField7 = ClosedEnum<
  typeof SimpleFieldSelectionField7
>;

export const SimpleFieldSelectionField6 = {
  QuestionLength: "questionLength",
} as const;
export type SimpleFieldSelectionField6 = ClosedEnum<
  typeof SimpleFieldSelectionField6
>;

export const SimpleFieldSelectionField5 = {
  Question: "question",
} as const;
export type SimpleFieldSelectionField5 = ClosedEnum<
  typeof SimpleFieldSelectionField5
>;

export const SimpleFieldSelectionField4 = {
  OrganizationId: "organizationId",
} as const;
export type SimpleFieldSelectionField4 = ClosedEnum<
  typeof SimpleFieldSelectionField4
>;

export const SimpleFieldSelectionField3 = {
  MessagesCount: "messagesCount",
} as const;
export type SimpleFieldSelectionField3 = ClosedEnum<
  typeof SimpleFieldSelectionField3
>;

export const SimpleFieldSelectionField2 = {
  MessageIds: "messageIds",
} as const;
export type SimpleFieldSelectionField2 = ClosedEnum<
  typeof SimpleFieldSelectionField2
>;

export const SimpleFieldSelectionField1 = {
  Id: "id",
} as const;
export type SimpleFieldSelectionField1 = ClosedEnum<
  typeof SimpleFieldSelectionField1
>;

export type SimpleFieldSelectionField =
  | SimpleFieldSelectionField1
  | SimpleFieldSelectionField2
  | SimpleFieldSelectionField3
  | SimpleFieldSelectionField4
  | SimpleFieldSelectionField5
  | SimpleFieldSelectionField6
  | SimpleFieldSelectionField7
  | SimpleFieldSelectionField8
  | SimpleFieldSelectionField9
  | SimpleFieldSelectionField10
  | SimpleFieldSelectionField11
  | SimpleFieldSelectionField12
  | SimpleFieldSelectionField13
  | SimpleFieldSelectionField14
  | SimpleFieldSelectionField15
  | SimpleFieldSelectionField16
  | SimpleFieldSelectionField17
  | SimpleFieldSelectionField18
  | SimpleFieldSelectionField19
  | SimpleFieldSelectionField20
  | SimpleFieldSelectionField21
  | SimpleFieldSelectionField22
  | SimpleFieldSelectionField23
  | SimpleFieldSelectionField24
  | SimpleFieldSelectionField25
  | SimpleFieldSelectionField26
  | SimpleFieldSelectionField27
  | SimpleFieldSelectionField28
  | SimpleFieldSelectionField29
  | SimpleFieldSelectionField30
  | SimpleFieldSelectionField31;

export type SimpleFieldSelection = {
  type: SimpleFieldSelectionType;
  field:
    | SimpleFieldSelectionField1
    | SimpleFieldSelectionField2
    | SimpleFieldSelectionField3
    | SimpleFieldSelectionField4
    | SimpleFieldSelectionField5
    | SimpleFieldSelectionField6
    | SimpleFieldSelectionField7
    | SimpleFieldSelectionField8
    | SimpleFieldSelectionField9
    | SimpleFieldSelectionField10
    | SimpleFieldSelectionField11
    | SimpleFieldSelectionField12
    | SimpleFieldSelectionField13
    | SimpleFieldSelectionField14
    | SimpleFieldSelectionField15
    | SimpleFieldSelectionField16
    | SimpleFieldSelectionField17
    | SimpleFieldSelectionField18
    | SimpleFieldSelectionField19
    | SimpleFieldSelectionField20
    | SimpleFieldSelectionField21
    | SimpleFieldSelectionField22
    | SimpleFieldSelectionField23
    | SimpleFieldSelectionField24
    | SimpleFieldSelectionField25
    | SimpleFieldSelectionField26
    | SimpleFieldSelectionField27
    | SimpleFieldSelectionField28
    | SimpleFieldSelectionField29
    | SimpleFieldSelectionField30
    | SimpleFieldSelectionField31;
};

/** @internal */
export const SimpleFieldSelectionType$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionType
> = z.nativeEnum(SimpleFieldSelectionType);

/** @internal */
export const SimpleFieldSelectionType$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionType
> = SimpleFieldSelectionType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionType$ {
  /** @deprecated use `SimpleFieldSelectionType$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionType$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionType$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionType$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField31$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField31
> = z.nativeEnum(SimpleFieldSelectionField31);

/** @internal */
export const SimpleFieldSelectionField31$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField31
> = SimpleFieldSelectionField31$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField31$ {
  /** @deprecated use `SimpleFieldSelectionField31$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField31$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField31$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField31$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField30$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField30
> = z.nativeEnum(SimpleFieldSelectionField30);

/** @internal */
export const SimpleFieldSelectionField30$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField30
> = SimpleFieldSelectionField30$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField30$ {
  /** @deprecated use `SimpleFieldSelectionField30$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField30$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField30$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField30$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField29$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField29
> = z.nativeEnum(SimpleFieldSelectionField29);

/** @internal */
export const SimpleFieldSelectionField29$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField29
> = SimpleFieldSelectionField29$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField29$ {
  /** @deprecated use `SimpleFieldSelectionField29$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField29$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField29$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField29$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField28$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField28
> = z.nativeEnum(SimpleFieldSelectionField28);

/** @internal */
export const SimpleFieldSelectionField28$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField28
> = SimpleFieldSelectionField28$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField28$ {
  /** @deprecated use `SimpleFieldSelectionField28$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField28$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField28$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField28$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField27$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField27
> = z.nativeEnum(SimpleFieldSelectionField27);

/** @internal */
export const SimpleFieldSelectionField27$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField27
> = SimpleFieldSelectionField27$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField27$ {
  /** @deprecated use `SimpleFieldSelectionField27$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField27$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField27$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField27$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField26$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField26
> = z.nativeEnum(SimpleFieldSelectionField26);

/** @internal */
export const SimpleFieldSelectionField26$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField26
> = SimpleFieldSelectionField26$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField26$ {
  /** @deprecated use `SimpleFieldSelectionField26$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField26$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField26$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField26$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField25$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField25
> = z.nativeEnum(SimpleFieldSelectionField25);

/** @internal */
export const SimpleFieldSelectionField25$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField25
> = SimpleFieldSelectionField25$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField25$ {
  /** @deprecated use `SimpleFieldSelectionField25$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField25$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField25$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField25$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField24$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField24
> = z.nativeEnum(SimpleFieldSelectionField24);

/** @internal */
export const SimpleFieldSelectionField24$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField24
> = SimpleFieldSelectionField24$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField24$ {
  /** @deprecated use `SimpleFieldSelectionField24$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField24$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField24$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField24$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField23$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField23
> = z.nativeEnum(SimpleFieldSelectionField23);

/** @internal */
export const SimpleFieldSelectionField23$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField23
> = SimpleFieldSelectionField23$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField23$ {
  /** @deprecated use `SimpleFieldSelectionField23$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField23$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField23$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField23$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField22$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField22
> = z.nativeEnum(SimpleFieldSelectionField22);

/** @internal */
export const SimpleFieldSelectionField22$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField22
> = SimpleFieldSelectionField22$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField22$ {
  /** @deprecated use `SimpleFieldSelectionField22$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField22$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField22$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField22$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField21$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField21
> = z.nativeEnum(SimpleFieldSelectionField21);

/** @internal */
export const SimpleFieldSelectionField21$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField21
> = SimpleFieldSelectionField21$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField21$ {
  /** @deprecated use `SimpleFieldSelectionField21$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField21$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField21$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField21$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField20$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField20
> = z.nativeEnum(SimpleFieldSelectionField20);

/** @internal */
export const SimpleFieldSelectionField20$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField20
> = SimpleFieldSelectionField20$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField20$ {
  /** @deprecated use `SimpleFieldSelectionField20$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField20$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField20$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField20$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField19$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField19
> = z.nativeEnum(SimpleFieldSelectionField19);

/** @internal */
export const SimpleFieldSelectionField19$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField19
> = SimpleFieldSelectionField19$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField19$ {
  /** @deprecated use `SimpleFieldSelectionField19$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField19$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField19$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField19$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField18$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField18
> = z.nativeEnum(SimpleFieldSelectionField18);

/** @internal */
export const SimpleFieldSelectionField18$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField18
> = SimpleFieldSelectionField18$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField18$ {
  /** @deprecated use `SimpleFieldSelectionField18$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField18$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField18$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField18$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField17$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField17
> = z.nativeEnum(SimpleFieldSelectionField17);

/** @internal */
export const SimpleFieldSelectionField17$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField17
> = SimpleFieldSelectionField17$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField17$ {
  /** @deprecated use `SimpleFieldSelectionField17$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField17$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField17$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField17$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField16$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField16
> = z.nativeEnum(SimpleFieldSelectionField16);

/** @internal */
export const SimpleFieldSelectionField16$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField16
> = SimpleFieldSelectionField16$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField16$ {
  /** @deprecated use `SimpleFieldSelectionField16$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField16$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField16$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField16$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField15$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField15
> = z.nativeEnum(SimpleFieldSelectionField15);

/** @internal */
export const SimpleFieldSelectionField15$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField15
> = SimpleFieldSelectionField15$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField15$ {
  /** @deprecated use `SimpleFieldSelectionField15$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField15$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField15$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField15$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField14$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField14
> = z.nativeEnum(SimpleFieldSelectionField14);

/** @internal */
export const SimpleFieldSelectionField14$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField14
> = SimpleFieldSelectionField14$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField14$ {
  /** @deprecated use `SimpleFieldSelectionField14$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField14$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField14$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField14$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField13$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField13
> = z.nativeEnum(SimpleFieldSelectionField13);

/** @internal */
export const SimpleFieldSelectionField13$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField13
> = SimpleFieldSelectionField13$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField13$ {
  /** @deprecated use `SimpleFieldSelectionField13$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField13$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField13$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField13$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField12$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField12
> = z.nativeEnum(SimpleFieldSelectionField12);

/** @internal */
export const SimpleFieldSelectionField12$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField12
> = SimpleFieldSelectionField12$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField12$ {
  /** @deprecated use `SimpleFieldSelectionField12$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField12$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField12$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField12$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField11$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField11
> = z.nativeEnum(SimpleFieldSelectionField11);

/** @internal */
export const SimpleFieldSelectionField11$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField11
> = SimpleFieldSelectionField11$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField11$ {
  /** @deprecated use `SimpleFieldSelectionField11$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField11$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField11$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField11$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField10$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField10
> = z.nativeEnum(SimpleFieldSelectionField10);

/** @internal */
export const SimpleFieldSelectionField10$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField10
> = SimpleFieldSelectionField10$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField10$ {
  /** @deprecated use `SimpleFieldSelectionField10$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField10$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField10$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField10$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField9$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField9
> = z.nativeEnum(SimpleFieldSelectionField9);

/** @internal */
export const SimpleFieldSelectionField9$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField9
> = SimpleFieldSelectionField9$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField9$ {
  /** @deprecated use `SimpleFieldSelectionField9$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField9$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField9$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField9$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField8$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField8
> = z.nativeEnum(SimpleFieldSelectionField8);

/** @internal */
export const SimpleFieldSelectionField8$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField8
> = SimpleFieldSelectionField8$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField8$ {
  /** @deprecated use `SimpleFieldSelectionField8$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField8$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField8$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField8$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField7$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField7
> = z.nativeEnum(SimpleFieldSelectionField7);

/** @internal */
export const SimpleFieldSelectionField7$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField7
> = SimpleFieldSelectionField7$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField7$ {
  /** @deprecated use `SimpleFieldSelectionField7$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField7$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField7$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField7$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField6$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField6
> = z.nativeEnum(SimpleFieldSelectionField6);

/** @internal */
export const SimpleFieldSelectionField6$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField6
> = SimpleFieldSelectionField6$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField6$ {
  /** @deprecated use `SimpleFieldSelectionField6$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField6$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField6$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField6$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField5$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField5
> = z.nativeEnum(SimpleFieldSelectionField5);

/** @internal */
export const SimpleFieldSelectionField5$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField5
> = SimpleFieldSelectionField5$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField5$ {
  /** @deprecated use `SimpleFieldSelectionField5$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField5$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField5$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField5$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField4$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField4
> = z.nativeEnum(SimpleFieldSelectionField4);

/** @internal */
export const SimpleFieldSelectionField4$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField4
> = SimpleFieldSelectionField4$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField4$ {
  /** @deprecated use `SimpleFieldSelectionField4$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField4$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField4$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField4$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField3$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField3
> = z.nativeEnum(SimpleFieldSelectionField3);

/** @internal */
export const SimpleFieldSelectionField3$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField3
> = SimpleFieldSelectionField3$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField3$ {
  /** @deprecated use `SimpleFieldSelectionField3$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField3$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField3$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField3$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField2$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField2
> = z.nativeEnum(SimpleFieldSelectionField2);

/** @internal */
export const SimpleFieldSelectionField2$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField2
> = SimpleFieldSelectionField2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField2$ {
  /** @deprecated use `SimpleFieldSelectionField2$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField2$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField2$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField2$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField1$inboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField1
> = z.nativeEnum(SimpleFieldSelectionField1);

/** @internal */
export const SimpleFieldSelectionField1$outboundSchema: z.ZodNativeEnum<
  typeof SimpleFieldSelectionField1
> = SimpleFieldSelectionField1$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField1$ {
  /** @deprecated use `SimpleFieldSelectionField1$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField1$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField1$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField1$outboundSchema;
}

/** @internal */
export const SimpleFieldSelectionField$inboundSchema: z.ZodType<
  SimpleFieldSelectionField,
  z.ZodTypeDef,
  unknown
> = z.union([
  SimpleFieldSelectionField1$inboundSchema,
  SimpleFieldSelectionField2$inboundSchema,
  SimpleFieldSelectionField3$inboundSchema,
  SimpleFieldSelectionField4$inboundSchema,
  SimpleFieldSelectionField5$inboundSchema,
  SimpleFieldSelectionField6$inboundSchema,
  SimpleFieldSelectionField7$inboundSchema,
  SimpleFieldSelectionField8$inboundSchema,
  SimpleFieldSelectionField9$inboundSchema,
  SimpleFieldSelectionField10$inboundSchema,
  SimpleFieldSelectionField11$inboundSchema,
  SimpleFieldSelectionField12$inboundSchema,
  SimpleFieldSelectionField13$inboundSchema,
  SimpleFieldSelectionField14$inboundSchema,
  SimpleFieldSelectionField15$inboundSchema,
  SimpleFieldSelectionField16$inboundSchema,
  SimpleFieldSelectionField17$inboundSchema,
  SimpleFieldSelectionField18$inboundSchema,
  SimpleFieldSelectionField19$inboundSchema,
  SimpleFieldSelectionField20$inboundSchema,
  SimpleFieldSelectionField21$inboundSchema,
  SimpleFieldSelectionField22$inboundSchema,
  SimpleFieldSelectionField23$inboundSchema,
  SimpleFieldSelectionField24$inboundSchema,
  SimpleFieldSelectionField25$inboundSchema,
  SimpleFieldSelectionField26$inboundSchema,
  SimpleFieldSelectionField27$inboundSchema,
  SimpleFieldSelectionField28$inboundSchema,
  SimpleFieldSelectionField29$inboundSchema,
  SimpleFieldSelectionField30$inboundSchema,
  SimpleFieldSelectionField31$inboundSchema,
]);

/** @internal */
export type SimpleFieldSelectionField$Outbound =
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string
  | string;

/** @internal */
export const SimpleFieldSelectionField$outboundSchema: z.ZodType<
  SimpleFieldSelectionField$Outbound,
  z.ZodTypeDef,
  SimpleFieldSelectionField
> = z.union([
  SimpleFieldSelectionField1$outboundSchema,
  SimpleFieldSelectionField2$outboundSchema,
  SimpleFieldSelectionField3$outboundSchema,
  SimpleFieldSelectionField4$outboundSchema,
  SimpleFieldSelectionField5$outboundSchema,
  SimpleFieldSelectionField6$outboundSchema,
  SimpleFieldSelectionField7$outboundSchema,
  SimpleFieldSelectionField8$outboundSchema,
  SimpleFieldSelectionField9$outboundSchema,
  SimpleFieldSelectionField10$outboundSchema,
  SimpleFieldSelectionField11$outboundSchema,
  SimpleFieldSelectionField12$outboundSchema,
  SimpleFieldSelectionField13$outboundSchema,
  SimpleFieldSelectionField14$outboundSchema,
  SimpleFieldSelectionField15$outboundSchema,
  SimpleFieldSelectionField16$outboundSchema,
  SimpleFieldSelectionField17$outboundSchema,
  SimpleFieldSelectionField18$outboundSchema,
  SimpleFieldSelectionField19$outboundSchema,
  SimpleFieldSelectionField20$outboundSchema,
  SimpleFieldSelectionField21$outboundSchema,
  SimpleFieldSelectionField22$outboundSchema,
  SimpleFieldSelectionField23$outboundSchema,
  SimpleFieldSelectionField24$outboundSchema,
  SimpleFieldSelectionField25$outboundSchema,
  SimpleFieldSelectionField26$outboundSchema,
  SimpleFieldSelectionField27$outboundSchema,
  SimpleFieldSelectionField28$outboundSchema,
  SimpleFieldSelectionField29$outboundSchema,
  SimpleFieldSelectionField30$outboundSchema,
  SimpleFieldSelectionField31$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelectionField$ {
  /** @deprecated use `SimpleFieldSelectionField$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelectionField$inboundSchema;
  /** @deprecated use `SimpleFieldSelectionField$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelectionField$outboundSchema;
  /** @deprecated use `SimpleFieldSelectionField$Outbound` instead. */
  export type Outbound = SimpleFieldSelectionField$Outbound;
}

export function simpleFieldSelectionFieldToJSON(
  simpleFieldSelectionField: SimpleFieldSelectionField,
): string {
  return JSON.stringify(
    SimpleFieldSelectionField$outboundSchema.parse(simpleFieldSelectionField),
  );
}

export function simpleFieldSelectionFieldFromJSON(
  jsonString: string,
): SafeParseResult<SimpleFieldSelectionField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimpleFieldSelectionField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimpleFieldSelectionField' from JSON`,
  );
}

/** @internal */
export const SimpleFieldSelection$inboundSchema: z.ZodType<
  SimpleFieldSelection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: SimpleFieldSelectionType$inboundSchema,
  field: z.union([
    SimpleFieldSelectionField1$inboundSchema,
    SimpleFieldSelectionField2$inboundSchema,
    SimpleFieldSelectionField3$inboundSchema,
    SimpleFieldSelectionField4$inboundSchema,
    SimpleFieldSelectionField5$inboundSchema,
    SimpleFieldSelectionField6$inboundSchema,
    SimpleFieldSelectionField7$inboundSchema,
    SimpleFieldSelectionField8$inboundSchema,
    SimpleFieldSelectionField9$inboundSchema,
    SimpleFieldSelectionField10$inboundSchema,
    SimpleFieldSelectionField11$inboundSchema,
    SimpleFieldSelectionField12$inboundSchema,
    SimpleFieldSelectionField13$inboundSchema,
    SimpleFieldSelectionField14$inboundSchema,
    SimpleFieldSelectionField15$inboundSchema,
    SimpleFieldSelectionField16$inboundSchema,
    SimpleFieldSelectionField17$inboundSchema,
    SimpleFieldSelectionField18$inboundSchema,
    SimpleFieldSelectionField19$inboundSchema,
    SimpleFieldSelectionField20$inboundSchema,
    SimpleFieldSelectionField21$inboundSchema,
    SimpleFieldSelectionField22$inboundSchema,
    SimpleFieldSelectionField23$inboundSchema,
    SimpleFieldSelectionField24$inboundSchema,
    SimpleFieldSelectionField25$inboundSchema,
    SimpleFieldSelectionField26$inboundSchema,
    SimpleFieldSelectionField27$inboundSchema,
    SimpleFieldSelectionField28$inboundSchema,
    SimpleFieldSelectionField29$inboundSchema,
    SimpleFieldSelectionField30$inboundSchema,
    SimpleFieldSelectionField31$inboundSchema,
  ]),
});

/** @internal */
export type SimpleFieldSelection$Outbound = {
  type: string;
  field:
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string
    | string;
};

/** @internal */
export const SimpleFieldSelection$outboundSchema: z.ZodType<
  SimpleFieldSelection$Outbound,
  z.ZodTypeDef,
  SimpleFieldSelection
> = z.object({
  type: SimpleFieldSelectionType$outboundSchema,
  field: z.union([
    SimpleFieldSelectionField1$outboundSchema,
    SimpleFieldSelectionField2$outboundSchema,
    SimpleFieldSelectionField3$outboundSchema,
    SimpleFieldSelectionField4$outboundSchema,
    SimpleFieldSelectionField5$outboundSchema,
    SimpleFieldSelectionField6$outboundSchema,
    SimpleFieldSelectionField7$outboundSchema,
    SimpleFieldSelectionField8$outboundSchema,
    SimpleFieldSelectionField9$outboundSchema,
    SimpleFieldSelectionField10$outboundSchema,
    SimpleFieldSelectionField11$outboundSchema,
    SimpleFieldSelectionField12$outboundSchema,
    SimpleFieldSelectionField13$outboundSchema,
    SimpleFieldSelectionField14$outboundSchema,
    SimpleFieldSelectionField15$outboundSchema,
    SimpleFieldSelectionField16$outboundSchema,
    SimpleFieldSelectionField17$outboundSchema,
    SimpleFieldSelectionField18$outboundSchema,
    SimpleFieldSelectionField19$outboundSchema,
    SimpleFieldSelectionField20$outboundSchema,
    SimpleFieldSelectionField21$outboundSchema,
    SimpleFieldSelectionField22$outboundSchema,
    SimpleFieldSelectionField23$outboundSchema,
    SimpleFieldSelectionField24$outboundSchema,
    SimpleFieldSelectionField25$outboundSchema,
    SimpleFieldSelectionField26$outboundSchema,
    SimpleFieldSelectionField27$outboundSchema,
    SimpleFieldSelectionField28$outboundSchema,
    SimpleFieldSelectionField29$outboundSchema,
    SimpleFieldSelectionField30$outboundSchema,
    SimpleFieldSelectionField31$outboundSchema,
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimpleFieldSelection$ {
  /** @deprecated use `SimpleFieldSelection$inboundSchema` instead. */
  export const inboundSchema = SimpleFieldSelection$inboundSchema;
  /** @deprecated use `SimpleFieldSelection$outboundSchema` instead. */
  export const outboundSchema = SimpleFieldSelection$outboundSchema;
  /** @deprecated use `SimpleFieldSelection$Outbound` instead. */
  export type Outbound = SimpleFieldSelection$Outbound;
}

export function simpleFieldSelectionToJSON(
  simpleFieldSelection: SimpleFieldSelection,
): string {
  return JSON.stringify(
    SimpleFieldSelection$outboundSchema.parse(simpleFieldSelection),
  );
}

export function simpleFieldSelectionFromJSON(
  jsonString: string,
): SafeParseResult<SimpleFieldSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimpleFieldSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimpleFieldSelection' from JSON`,
  );
}
