/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SupportTicketMessage,
  SupportTicketMessage$inboundSchema,
  SupportTicketMessage$Outbound,
  SupportTicketMessage$outboundSchema,
} from "./supportticketmessage.js";

/**
 * The unique identifier for the user. This value is sent by the inkeep widget.
 */
export type SupportTicketConversationId = string | number;

/**
 * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
 */
export type SupportTicketConversationUserId = string | number;

/**
 * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
 */
export type SupportTicketConversationUserProperties = {
  /**
   * The unique identifier for the user. This value is sent by the inkeep widget.
   */
  id?: string | number | null | undefined;
  /**
   * The type of identification for the user. This value is sent by the inkeep widget.
   */
  identificationType?: string | null | undefined;
  /**
   * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userId?: string | number | null | undefined;
  /**
   * The name of the support agent assigned to the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  supportAgentName?: string | null | undefined;
  /**
   * The type of user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userType?: string | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const SupportTicketConversationVisibility = {
  Private: "private",
  Public: "public",
} as const;
export type SupportTicketConversationVisibility = ClosedEnum<
  typeof SupportTicketConversationVisibility
>;

export type SupportTicketConversation = {
  id: string;
  externalId: string | null;
  externalUrl: string | null;
  type: "support_ticket";
  supportTicketConversationId: string | null;
  createdAt: string;
  updatedAt: string;
  projectId: string | null;
  integrationId: string | null;
  /**
   * A customizable collection of custom properties or attributes.
   */
  properties?: { [k: string]: any } | null | undefined;
  /**
   * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
   */
  userProperties?: SupportTicketConversationUserProperties | null | undefined;
  tags?: Array<string> | null | undefined;
  visibility: SupportTicketConversationVisibility | null;
  /**
   * The messages in the conversation. Must be at least one message.
   */
  messages: Array<SupportTicketMessage>;
};

/** @internal */
export const SupportTicketConversationId$inboundSchema: z.ZodType<
  SupportTicketConversationId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type SupportTicketConversationId$Outbound = string | number;

/** @internal */
export const SupportTicketConversationId$outboundSchema: z.ZodType<
  SupportTicketConversationId$Outbound,
  z.ZodTypeDef,
  SupportTicketConversationId
> = z.union([z.string(), z.number()]);

export function supportTicketConversationIdToJSON(
  supportTicketConversationId: SupportTicketConversationId,
): string {
  return JSON.stringify(
    SupportTicketConversationId$outboundSchema.parse(
      supportTicketConversationId,
    ),
  );
}
export function supportTicketConversationIdFromJSON(
  jsonString: string,
): SafeParseResult<SupportTicketConversationId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportTicketConversationId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportTicketConversationId' from JSON`,
  );
}

/** @internal */
export const SupportTicketConversationUserId$inboundSchema: z.ZodType<
  SupportTicketConversationUserId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type SupportTicketConversationUserId$Outbound = string | number;

/** @internal */
export const SupportTicketConversationUserId$outboundSchema: z.ZodType<
  SupportTicketConversationUserId$Outbound,
  z.ZodTypeDef,
  SupportTicketConversationUserId
> = z.union([z.string(), z.number()]);

export function supportTicketConversationUserIdToJSON(
  supportTicketConversationUserId: SupportTicketConversationUserId,
): string {
  return JSON.stringify(
    SupportTicketConversationUserId$outboundSchema.parse(
      supportTicketConversationUserId,
    ),
  );
}
export function supportTicketConversationUserIdFromJSON(
  jsonString: string,
): SafeParseResult<SupportTicketConversationUserId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportTicketConversationUserId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportTicketConversationUserId' from JSON`,
  );
}

/** @internal */
export const SupportTicketConversationUserProperties$inboundSchema: z.ZodType<
  SupportTicketConversationUserProperties,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.nullable(z.union([z.string(), z.number()])).optional(),
    identificationType: z.nullable(z.string()).optional(),
    userId: z.nullable(z.union([z.string(), z.number()])).optional(),
    supportAgentName: z.nullable(z.string()).optional(),
    userType: z.nullable(z.string()).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type SupportTicketConversationUserProperties$Outbound = {
  id?: string | number | null | undefined;
  identificationType?: string | null | undefined;
  userId?: string | number | null | undefined;
  supportAgentName?: string | null | undefined;
  userType?: string | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const SupportTicketConversationUserProperties$outboundSchema: z.ZodType<
  SupportTicketConversationUserProperties$Outbound,
  z.ZodTypeDef,
  SupportTicketConversationUserProperties
> = z.object({
  id: z.nullable(z.union([z.string(), z.number()])).optional(),
  identificationType: z.nullable(z.string()).optional(),
  userId: z.nullable(z.union([z.string(), z.number()])).optional(),
  supportAgentName: z.nullable(z.string()).optional(),
  userType: z.nullable(z.string()).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function supportTicketConversationUserPropertiesToJSON(
  supportTicketConversationUserProperties:
    SupportTicketConversationUserProperties,
): string {
  return JSON.stringify(
    SupportTicketConversationUserProperties$outboundSchema.parse(
      supportTicketConversationUserProperties,
    ),
  );
}
export function supportTicketConversationUserPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<
  SupportTicketConversationUserProperties,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SupportTicketConversationUserProperties$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SupportTicketConversationUserProperties' from JSON`,
  );
}

/** @internal */
export const SupportTicketConversationVisibility$inboundSchema: z.ZodNativeEnum<
  typeof SupportTicketConversationVisibility
> = z.nativeEnum(SupportTicketConversationVisibility);
/** @internal */
export const SupportTicketConversationVisibility$outboundSchema:
  z.ZodNativeEnum<typeof SupportTicketConversationVisibility> =
    SupportTicketConversationVisibility$inboundSchema;

/** @internal */
export const SupportTicketConversation$inboundSchema: z.ZodType<
  SupportTicketConversation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  externalUrl: z.nullable(z.string()),
  type: z.literal("support_ticket"),
  supportTicketConversationId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => SupportTicketConversationUserProperties$inboundSchema),
  ).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  visibility: z.nullable(SupportTicketConversationVisibility$inboundSchema),
  messages: z.array(SupportTicketMessage$inboundSchema),
});
/** @internal */
export type SupportTicketConversation$Outbound = {
  id: string;
  externalId: string | null;
  externalUrl: string | null;
  type: "support_ticket";
  supportTicketConversationId: string | null;
  createdAt: string;
  updatedAt: string;
  projectId: string | null;
  integrationId: string | null;
  properties?: { [k: string]: any } | null | undefined;
  userProperties?:
    | SupportTicketConversationUserProperties$Outbound
    | null
    | undefined;
  tags?: Array<string> | null | undefined;
  visibility: string | null;
  messages: Array<SupportTicketMessage$Outbound>;
};

/** @internal */
export const SupportTicketConversation$outboundSchema: z.ZodType<
  SupportTicketConversation$Outbound,
  z.ZodTypeDef,
  SupportTicketConversation
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  externalUrl: z.nullable(z.string()),
  type: z.literal("support_ticket"),
  supportTicketConversationId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => SupportTicketConversationUserProperties$outboundSchema),
  ).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  visibility: z.nullable(SupportTicketConversationVisibility$outboundSchema),
  messages: z.array(SupportTicketMessage$outboundSchema),
});

export function supportTicketConversationToJSON(
  supportTicketConversation: SupportTicketConversation,
): string {
  return JSON.stringify(
    SupportTicketConversation$outboundSchema.parse(supportTicketConversation),
  );
}
export function supportTicketConversationFromJSON(
  jsonString: string,
): SafeParseResult<SupportTicketConversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportTicketConversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportTicketConversation' from JSON`,
  );
}
