/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SupportCopilotMessage,
  SupportCopilotMessage$inboundSchema,
  SupportCopilotMessage$Outbound,
  SupportCopilotMessage$outboundSchema,
} from "./supportcopilotmessage.js";

/**
 * The unique identifier for the user. This value is sent by the inkeep widget.
 */
export type SupportCopilotConversationId = string | number;

/**
 * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
 */
export type SupportCopilotConversationUserId = string | number;

/**
 * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
 */
export type SupportCopilotConversationUserProperties = {
  /**
   * The unique identifier for the user. This value is sent by the inkeep widget.
   */
  id?: string | number | null | undefined;
  /**
   * The type of identification for the user. This value is sent by the inkeep widget.
   */
  identificationType?: string | null | undefined;
  /**
   * The unique identifier for the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userId?: string | number | null | undefined;
  /**
   * The name of the support agent assigned to the user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  supportAgentName?: string | null | undefined;
  /**
   * The type of user. This value is sent by the Inkeep Support Agent Copilot. This value is used to create the graphs on the Inkeep Portal.
   */
  userType?: string | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const SupportCopilotConversationVisibility = {
  Private: "private",
  Public: "public",
} as const;
export type SupportCopilotConversationVisibility = ClosedEnum<
  typeof SupportCopilotConversationVisibility
>;

export type SupportCopilotConversation = {
  id: string;
  externalId: string | null;
  externalUrl: string | null;
  type: "support_copilot";
  supportTicketConversationId: string | null;
  createdAt: string;
  updatedAt: string;
  projectId: string | null;
  integrationId: string | null;
  /**
   * A customizable collection of custom properties or attributes.
   */
  properties?: { [k: string]: any } | null | undefined;
  /**
   * A customizable collection of custom properties or attributes. Some properties have first class support for the Inkeep Portal or Widget and are noted in the description.
   */
  userProperties?: SupportCopilotConversationUserProperties | null | undefined;
  tags?: Array<string> | null | undefined;
  visibility: SupportCopilotConversationVisibility | null;
  /**
   * The messages in the conversation. Must be at least one message.
   */
  messages: Array<SupportCopilotMessage>;
};

/** @internal */
export const SupportCopilotConversationId$inboundSchema: z.ZodType<
  SupportCopilotConversationId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type SupportCopilotConversationId$Outbound = string | number;

/** @internal */
export const SupportCopilotConversationId$outboundSchema: z.ZodType<
  SupportCopilotConversationId$Outbound,
  z.ZodTypeDef,
  SupportCopilotConversationId
> = z.union([z.string(), z.number()]);

export function supportCopilotConversationIdToJSON(
  supportCopilotConversationId: SupportCopilotConversationId,
): string {
  return JSON.stringify(
    SupportCopilotConversationId$outboundSchema.parse(
      supportCopilotConversationId,
    ),
  );
}
export function supportCopilotConversationIdFromJSON(
  jsonString: string,
): SafeParseResult<SupportCopilotConversationId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportCopilotConversationId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportCopilotConversationId' from JSON`,
  );
}

/** @internal */
export const SupportCopilotConversationUserId$inboundSchema: z.ZodType<
  SupportCopilotConversationUserId,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number()]);
/** @internal */
export type SupportCopilotConversationUserId$Outbound = string | number;

/** @internal */
export const SupportCopilotConversationUserId$outboundSchema: z.ZodType<
  SupportCopilotConversationUserId$Outbound,
  z.ZodTypeDef,
  SupportCopilotConversationUserId
> = z.union([z.string(), z.number()]);

export function supportCopilotConversationUserIdToJSON(
  supportCopilotConversationUserId: SupportCopilotConversationUserId,
): string {
  return JSON.stringify(
    SupportCopilotConversationUserId$outboundSchema.parse(
      supportCopilotConversationUserId,
    ),
  );
}
export function supportCopilotConversationUserIdFromJSON(
  jsonString: string,
): SafeParseResult<SupportCopilotConversationUserId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportCopilotConversationUserId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportCopilotConversationUserId' from JSON`,
  );
}

/** @internal */
export const SupportCopilotConversationUserProperties$inboundSchema: z.ZodType<
  SupportCopilotConversationUserProperties,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.nullable(z.union([z.string(), z.number()])).optional(),
    identificationType: z.nullable(z.string()).optional(),
    userId: z.nullable(z.union([z.string(), z.number()])).optional(),
    supportAgentName: z.nullable(z.string()).optional(),
    userType: z.nullable(z.string()).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type SupportCopilotConversationUserProperties$Outbound = {
  id?: string | number | null | undefined;
  identificationType?: string | null | undefined;
  userId?: string | number | null | undefined;
  supportAgentName?: string | null | undefined;
  userType?: string | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const SupportCopilotConversationUserProperties$outboundSchema: z.ZodType<
  SupportCopilotConversationUserProperties$Outbound,
  z.ZodTypeDef,
  SupportCopilotConversationUserProperties
> = z.object({
  id: z.nullable(z.union([z.string(), z.number()])).optional(),
  identificationType: z.nullable(z.string()).optional(),
  userId: z.nullable(z.union([z.string(), z.number()])).optional(),
  supportAgentName: z.nullable(z.string()).optional(),
  userType: z.nullable(z.string()).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function supportCopilotConversationUserPropertiesToJSON(
  supportCopilotConversationUserProperties:
    SupportCopilotConversationUserProperties,
): string {
  return JSON.stringify(
    SupportCopilotConversationUserProperties$outboundSchema.parse(
      supportCopilotConversationUserProperties,
    ),
  );
}
export function supportCopilotConversationUserPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<
  SupportCopilotConversationUserProperties,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SupportCopilotConversationUserProperties$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SupportCopilotConversationUserProperties' from JSON`,
  );
}

/** @internal */
export const SupportCopilotConversationVisibility$inboundSchema:
  z.ZodNativeEnum<typeof SupportCopilotConversationVisibility> = z.nativeEnum(
    SupportCopilotConversationVisibility,
  );
/** @internal */
export const SupportCopilotConversationVisibility$outboundSchema:
  z.ZodNativeEnum<typeof SupportCopilotConversationVisibility> =
    SupportCopilotConversationVisibility$inboundSchema;

/** @internal */
export const SupportCopilotConversation$inboundSchema: z.ZodType<
  SupportCopilotConversation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  externalUrl: z.nullable(z.string()),
  type: z.literal("support_copilot"),
  supportTicketConversationId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => SupportCopilotConversationUserProperties$inboundSchema),
  ).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  visibility: z.nullable(SupportCopilotConversationVisibility$inboundSchema),
  messages: z.array(SupportCopilotMessage$inboundSchema),
});
/** @internal */
export type SupportCopilotConversation$Outbound = {
  id: string;
  externalId: string | null;
  externalUrl: string | null;
  type: "support_copilot";
  supportTicketConversationId: string | null;
  createdAt: string;
  updatedAt: string;
  projectId: string | null;
  integrationId: string | null;
  properties?: { [k: string]: any } | null | undefined;
  userProperties?:
    | SupportCopilotConversationUserProperties$Outbound
    | null
    | undefined;
  tags?: Array<string> | null | undefined;
  visibility: string | null;
  messages: Array<SupportCopilotMessage$Outbound>;
};

/** @internal */
export const SupportCopilotConversation$outboundSchema: z.ZodType<
  SupportCopilotConversation$Outbound,
  z.ZodTypeDef,
  SupportCopilotConversation
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  externalUrl: z.nullable(z.string()),
  type: z.literal("support_copilot"),
  supportTicketConversationId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  projectId: z.nullable(z.string()),
  integrationId: z.nullable(z.string()),
  properties: z.nullable(z.record(z.any())).optional(),
  userProperties: z.nullable(
    z.lazy(() => SupportCopilotConversationUserProperties$outboundSchema),
  ).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  visibility: z.nullable(SupportCopilotConversationVisibility$outboundSchema),
  messages: z.array(SupportCopilotMessage$outboundSchema),
});

export function supportCopilotConversationToJSON(
  supportCopilotConversation: SupportCopilotConversation,
): string {
  return JSON.stringify(
    SupportCopilotConversation$outboundSchema.parse(supportCopilotConversation),
  );
}
export function supportCopilotConversationFromJSON(
  jsonString: string,
): SafeParseResult<SupportCopilotConversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportCopilotConversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportCopilotConversation' from JSON`,
  );
}
